### PR TITLE
SmallRye Rest Client 1.2

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
- [X] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [X] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
locally checked with -Pmicroprofile-tcks

**Review by Ladicek — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
For the white space reverting changes to make sense, I'll squash the commits

**Comment by kenfinnigan** [comment]
Is the linux build finished?

**Comment by michalszynkiewicz** [comment]
All the links to builds return 404 to me so I'm not sure...
It succeeded for my commit, Ladislav removed two spaces in his.

**Comment by michalszynkiewicz** [comment]
Sorry if I shouldn't have pushed it

**Comment by kenfinnigan** [comment]
no worries

**Comment by Ladicek** [comment]
@michalszynkiewicz FYI, you need to be logged into Jenkins to see build logs. No, I still don't know why :-) And the Linux build passed as well: https://ci.wildfly-swarm.io/job/thorntail-pull-request-linux/843/

**Pull request merged**
