### PR TITLE
Provide information about boot-time performance.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Motivation
----------

We've gotten slow, apparently.  Why?

Modifications
-------------

Add instrumentation, printed after boot, to tell us where we are spending
our time.

Result
------

More log output!

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by gastaldi** [comment]
retest this please

**Comment by gastaldi** [comment]
Retest this please

**Review by kenfinnigan — APPROVED** [review]
Verify brief review, trusting you otherwise ;-)

**Comment by bobmcwhirter** [comment]
retest this please

**Pull request merged**
