### PR TITLE
Utilize the SmallRye OpenAPI library (smallrye-open-api 1.0.0)

### PR DESCRIPTION
**Pull request by EricWittmann**
This fixes issue https://github.com/thorntail/thorntail/issues/972 for v2 of Thorntail.

Please take a look at the fraction module configuration.  I think it's OK but wouldn't bet much money on it.  Otherwise it's mostly the removal of code. :)

- [*] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [*] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [*] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by sberyozkin — APPROVED** [review]
IMHO this is ready to be merged

**Comment by sberyozkin** [comment]
OpenAPI TCK test fails on Win, I would've merged if some other non-related test failed there but I guess it may require a bit more investigation ?

**Comment by EricWittmann** [comment]
It did?  That's odd - I tested the build on Windows.  The OpenAPI stuff passed but all the docker stuff failed because I don't have docker installed on my windows box. 

Looks like Fault Tolerance fails.  Some change I made affected FT somehow??

https://ci.wildfly-swarm.io/job/thorntail-pull-request-windows/454/testReport/

**Comment by EricWittmann** [comment]
The test failure is:  https://ci.wildfly-swarm.io/job/thorntail-pull-request-windows/io.thorntail.testsuite$thorntail-microprofile-tck-fault-tolerance/454/testReport/org.eclipse.microprofile.fault.tolerance.tck.bulkhead/BulkheadAsynchRetryTest/testBulkheadPassiveRetryMethodAsynchronous55/

Unrelated?

**Comment by sberyozkin** [comment]
Oops, my fault, I spotted:

2018-07-02 07:32:42,697 INFO  [org.jboss.weld.Bootstrap] (pool-1-thread-1) WELD-ENV-002001: Weld SE container internal shut down
java.nio.file.FileSystemException: C:\opt\jenkins\workspace\thorntail-pull-request-windows\testsuite\microprofile-tcks\openapi\target\wfswarmarquillian4461460192853962195.tmp: The process cannot access the file because it is being used by another process.

and got confused, sorry about it, will merge tomorrow then to give a bit more time for others to have a look ...thanks

**Pull request merged**
