### PR TITLE
SWARM-1317: update to jaxb 2.2.11

### PR DESCRIPTION
**Pull request by heiko-braun**
- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by heiko-braun** [comment]
This basically removes the duplicate jaxb dependency:

```
Status quo:

m2repo/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.7.4/jackson-module-jaxb-annotations-2.7.4.jar
m2repo/com/sun/xml/bind/jaxb-core/2.2.7/jaxb-core-2.2.7.jar
m2repo/com/sun/xml/bind/jaxb-impl/2.2.7/jaxb-impl-2.2.7.jar
m2repo/javax/xml/bind/jaxb-api/2.2.7/jaxb-api-2.2.7.jar
m2repo/org/glassfish/jaxb/codemodel/2.2.11.jbossorg-1/codemodel-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-core/2.2.11.jbossorg-1/jaxb-core-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-jxc/2.2.11.jbossorg-1/jaxb-jxc-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-runtime/2.2.11.jbossorg-1/jaxb-runtime-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-xjc/2.2.11.jbossorg-1/jaxb-xjc-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/txw2/2.2.11.jbossorg-1/txw2-2.2.11.jbossorg-1.jar
m2repo/org/jboss/resteasy/resteasy-jaxb-provider/3.0.19.Final/resteasy-jaxb-provider-3.0.19.Final.jar
m2repo/org/jboss/spec/javax/xml/bind/jboss-jaxb-api_2.2_spec/1.0.4.Final/jboss-jaxb-api_2.2_spec-1.0.4.Final.jar
m2repo/org/wildfly/swarm/jaxrs-jaxb/2017.6.0-SNAPSHOT/jaxrs-jaxb-2017.6.0-SNAPSHOT.jar
 
// with exclusions
 
m2repo/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.7.4/jackson-module-jaxb-annotations-2.7.4.jar
m2repo/org/glassfish/jaxb/codemodel/2.2.11.jbossorg-1/codemodel-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-core/2.2.11.jbossorg-1/jaxb-core-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-jxc/2.2.11.jbossorg-1/jaxb-jxc-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-runtime/2.2.11.jbossorg-1/jaxb-runtime-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/jaxb-xjc/2.2.11.jbossorg-1/jaxb-xjc-2.2.11.jbossorg-1.jar
m2repo/org/glassfish/jaxb/txw2/2.2.11.jbossorg-1/txw2-2.2.11.jbossorg-1.jar
m2repo/org/jboss/resteasy/resteasy-jaxb-provider/3.0.19.Final/resteasy-jaxb-provider-3.0.19.Final.jar
m2repo/org/jboss/spec/javax/xml/bind/jboss-jaxb-api_2.2_spec/1.0.4.Final/jboss-jaxb-api_2.2_spec-1.0.4.Final.jar
m2repo/org/wildfly/swarm/jaxrs-jaxb/2017.6.0-SNAPSHOT/jaxrs-jaxb-2017.6.0-SNAPSHOT.jar
```

**Comment by michalszynkiewicz** [comment]
Does it also remove istack:2.16, FastInfoset:1.2.12 and jsr173_api?

**Comment by heiko-braun** [comment]
@michalszynkiewicz 

> Does it also remove istack:2.16, FastInfoset:1.2.12 and jsr173_api?

Any idea how i can verify that? The above was a simple uberJar build, but apparently these deps are not included. Not even without my changes.

**Comment by michalszynkiewicz** [comment]
@heiko-braun as I wrote in the email, it should exclude it.
The PR looks good to me.

**Pull request merged**
