### PR TITLE
[THORN-2252][THORN-2440] update MP Metrics and MP Fault Tolerance

### PR DESCRIPTION
**Pull request by Ladicek**
- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft because we need https://github.com/smallrye/smallrye-fault-tolerance/pull/95 first.

**Review by jmartisk — COMMENTED** [review]
Just went through the Metrics changes and it looks good. It covers all needed tasks that are in the list that I've been gathering.

**Comment by Ladicek** [comment]
Thanks @jmartisk!

**Review by michalszynkiewicz — DISMISSED** [review]

**Comment by Ladicek** [comment]
Fixed test failures in RestClient + Metrics test.

**Review by michalszynkiewicz — APPROVED** [review]
Still looks good buy I don't know what you changed

**Comment by Ladicek** [comment]
This is the file I changed, everything else remained the same: https://github.com/thorntail/thorntail/pull/1300/files#diff-8b81cb36f954affe9b2ec2b34acd09a6 Tests should pass now, I hope :-) Thanks!

**Comment by michalszynkiewicz** [comment]
thanks

**Review by jmartisk — APPROVED** [review]

**Pull request merged**
