### PR TITLE
THORN-2091: Maven plugin for automated migration from WildFly Swarm to Thorntail

### PR DESCRIPTION
**Pull request by Ladicek**
Motivation
----------
The set of changes required to migrate from WildFly Swarm to Thorntail v2
is pretty small and is easy to automate. To help our users, we should provide
a Maven plugin that would perform all the necessary steps.

Modifications
-------------
Added one Mojo to the existing Thorntail Maven plugin that will scan `pom.xml`
files of a Maven project and perform all the changes required for migration
from WildFly Swarm to Thorntail v2.

Result
------
Users can just run

  mvn io.thorntail:thorntail-maven-plugin:2.0.1.Final-SNAPSHOT:migrate-from-wildfly-swarm

without having to do anything else.

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
Clearly I should add some documentation, but I think it's in a good-enough shape to undergo some scrutiny :-)

**Comment by sberyozkin** [comment]
IMHO this is a super nice addition which the users will appreciate, if no other reviews will follow in the next day or so then I will get it approved/merged

**Comment by michalszynkiewicz** [comment]
It looks good :)

It would be great if it had some tests.
Will it work for profiles as it is?

**Comment by Ladicek** [comment]
I'm working on adding a test as we speak.

Profiles -- very good point! Currently, no.

**Comment by Ladicek** [comment]
I just pushed a small test with a couple of small adjustments, and then realized I didn't add the support for profiles. Working on that now.

**Comment by sberyozkin** [comment]
If you'd like I can merge it now and you can then follow up with another PR

**Comment by Ladicek** [comment]
I rebased and refactored and added support for profiles.

**Review by michalszynkiewicz — DISMISSED** [review]

**Comment by Ladicek** [comment]
Ah, the test failed on Windows because of path separators. I'll try to fix.

**Comment by Ladicek** [comment]
Pushed a fix for the test on Windows.

**Comment by sberyozkin** [comment]
Usual suspect on Win...May be worth skipping it if it is on Win ?

**Comment by sberyozkin** [comment]
Hmm... I can't approve this PR.
@kenfinnigan, Ken, can you please look at the permissions again :-) ? 

I've added myself to the list of Reviewers for this PR but still can't approve. Though it looks like I can still merge it

**Review by sberyozkin — APPROVED** [review]

**Comment by sberyozkin** [comment]
Never mind :-), looks like when the reviewers are already available then one needs to self-request a review

**Comment by Ladicek** [comment]
Thanks @sberyozkin!

**Pull request merged**
