### PR TITLE
[THORN-2412] bump SmallRye Health Check 2.0

### PR DESCRIPTION
**Pull request by penehyba**
- [ ] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
add to whitelist

**Comment by Ladicek** [comment]
At least you will also have to change this: https://github.com/thorntail/thorntail/blob/master/fractions/microprofile/microprofile-health/src/main/resources/modules/org/eclipse/microprofile/health/main/module.xml#L5

**Comment by Ladicek** [comment]
It seems there are genuine TCK failures.

**Comment by Ladicek** [comment]
Still failing :-/

**Comment by juangon** [comment]
It fails in health TCK. Should this TCK be updated too in Thorntail?

**Comment by Ladicek** [comment]
Doesn't this PR update it already?

**Review by Ladicek — APPROVED** [review]

**Comment by juangon** [comment]
It passes for TCK but it fails for new Health check tests from here: https://github.com/penehyba/thorntail-test-suite/commits/health-check-20. Just saw there is another PR from @Ladicek , gonna check new tests with this new PR

**Comment by juangon** [comment]
Forget my previous comment, those tests have some slight things that should be changed. @penehyba I an gonna make a PR to your thorntail-test-suite branch soon

**Comment by Ladicek** [comment]
@juangon @penehyba BTW, here's a draft PR that updates the MP Metrics test to 2.0: https://github.com/rhoar-qe/thorntail-test-suite/pull/58. I decided that in case of breaking changes, it makes most sense to just fold all the previous versions (e.g. `microprofile-metrics-1.0` and `microprofile-metrics-1.1`) into the new module (`microprofile-metrics-2.0`). I think I'd do the same for MP Health 2.0.

**Comment by Ladicek** [comment]
@juangon @penehyba  Here's a draft PR for the MP Metrics 2.0 test for your convenience: https://github.com/rhoar-qe/thorntail-test-suite/pull/58

**Review by juangon — APPROVED** [review]

**Pull request merged**
