### PR TITLE
Switch to 1.3.x of config-api in community

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by scottmarlow** [comment]
Do the other config-api's also need to be updated/released, more specifically the mongo.config-api, cassandra.config-api, neo4j.config-api, orientdb.config-api?

**Comment by Ladicek** [comment]
I don't think the NoSQL config APIs need to be bumped, as they are not used in product (right?). What needs to be bumped is the Keycloak config API.

**Comment by scottmarlow** [comment]
Correct, the NoSQL config APIs are not in product.  Thanks for clarifying!

**Comment by heiko-braun** [comment]
@scottmarlow : @Ladicek is right. Only the ones shared with the prod build need to be bumped to avoid conflicts. 

And @Ladicek : The KC update is here https://github.com/wildfly-swarm/wildfly-swarm/pull/807

**Pull request merged**
