### PR TITLE
SWARM-1619: BOM should not include internal fractions

### PR DESCRIPTION
**Pull request by kenfinnigan**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------
BOM currently includes fractions that are marked internal.

Users should not be adding internal fractions as dependencies to their applications.

Modifications
-------------
Update fraction-plugin to version that filters out internal fractions from BOM creation.

Result
------
BOM no longer includes internal fractions

### CODE REVIEW

**Review by Ladicek — DISMISSED** [review]

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
@Ladicek any insight you can provide as to why testsuite-maven-plugin keeps failing with this PR would be appreciated.

Had a look at the test but couldn't see anything that would cause it not to find SERVLET or JAX-RS

**Comment by Ladicek** [comment]
@kenfinnigan Looking at https://ci.wildfly-swarm.io/job/wildfly-swarm-pull-request-linux/800/org.wildfly.swarm.testsuite$testsuite-maven-plugin/testReport/, it seems all the 3 failures are the same: when the test project is being built, Maven can't find a version for `org.wildfly.swarm:container`. That used to be a public API I think; is it no longer the case?

```
Exit code was non-zero: 1; command line and log = 
/opt/maven/apache-maven-3.3.9/bin/mvn -s /root/.m2/settings.xml -e --batch-mode -Dmaven.repo.local=/root/workspace/wildfly-swarm-pull-request-linux/.repository org.apache.maven.plugins:maven-clean-plugin:clean verify
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.wildfly.swarm:container:jar is missing. @ line 37, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.wildfly.swarm:container:jar is missing. @ line 37, column 17
```

**Comment by kenfinnigan** [comment]
From looking at the BOMs, yes `container` is no longer present in the BOM, but `container` will still be a dependency of other Fractions.

Maybe I need to rework the test a bit

**Comment by Ladicek** [comment]
So all the tests that are failing have a custom `main` method (aside: do we still wanna test that? I guess yes, for now), so they have an explicit dependency on `org.wildfly.swarm:container` right in their POM. I don't know how importing a `<dependencyManagement>` section from a BOM works, but I guess this doesn't work transitively?

**Comment by kenfinnigan** [comment]
@Ladicek tests work with this fix.

We can evaluate another time the validity of testing main() usage

**Comment by Ladicek** [comment]
I don't quite like the test change -- it bypasses the BOM, which is how Swarm is supposed to be consumed. At this point, I believe the BOM should include `container` -- it's fraction-ish for the purpose of generating the BOM, but not really a fraction, so the notion of "being internal" doesn't quite apply. I think.

**Comment by kenfinnigan** [comment]
Right, but `container` is always present as a transitive dependency through user facing fractions.

It's adding it directly that's the problem as users should not be adding that themselves.

Now I'm happy to remove the main() tests so that such a dependency isn't needed at all

**Comment by Ladicek** [comment]
I see. Makes sense. I filed https://issues.jboss.org/browse/SWARM-1709 and I'm now +1 to merge this.

**Comment by Ladicek** [comment]
Ah silly me -- I thought the fix you did bypasses the BOM for _all_ fractions -- but it's only for `container`. So it's actually fine.

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
