### PR TITLE
SWARM-1533 - Swarm fails to create if path to .m2/repository has spaces

### PR DESCRIPTION
**Pull request by nelsongraca**
It would be great if this can be merged on 2017.9.0

### CODE REVIEW

**Comment by heiko-braun** [comment]
test this please

**Review by heiko-braun — APPROVED** [review]
Looks good to me

**Comment by heiko-braun** [comment]
thanks @nelsongraca !

**Comment by nelsongraca** [comment]
@heiko-braun Thank you for accepting it.

**Pull request merged**
