### PR TITLE
https://issues.jboss.org/browse/THORN-2393: Thorntail-runner - JAX-RS…

### PR DESCRIPTION
**Pull request by bojanb1234**
… ClassNotFoundException

- [ ] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [ ] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by michalszynkiewicz — APPROVED** [review]
Thank you @bojanb1234 !

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
Thanks, will wait for the tests to finish and then merge.

**Comment by Ladicek** [comment]
The Linux JDK 11 failure is a known flaky test in MP FT TCK.

**Comment by Ladicek** [comment]
Thanks!

**Pull request merged**
