### PR TITLE
[THORN-1999] - Evaluate either Accept header OR query parameter to deli…

### PR DESCRIPTION
**Pull request by michbeck100**
…ver OpenAPI definition in JSON format

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by kenfinnigan** [comment]
add to whitelist

**Comment by michbeck100** [comment]
Semaphore CI failed with a strange error. @kenfinnigan can you explain this?

**Comment by kenfinnigan** [comment]
@michbeck100, Semaphore CI isn't the important job for this PR, as they're focused on 4.x branch PRs but I haven't found a way to disable it for master branch PRs.

Linux and Windows CI are the main ones to worry about for this PR

**Comment by michbeck100** [comment]
Ok, then you should have a look at the windows [build](https://ci.wildfly-swarm.io/job/thorntail-pull-request-windows/579/console) as the disk of the Jenkins slave seems to be full :-)

**Pull request merged**
