### PR TITLE
THORN-2360 Update XA datasource driver for MySQL

### PR DESCRIPTION
**Pull request by juangon**
- [X] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [X] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
Is that a difference between various MySQL JDBC driver versions?

**Comment by juangon** [comment]
@Ladicek . As what I see it changed since mysql connector Java 6.x onwards (until 5.x used other package)

**Comment by Ladicek** [comment]
Hmm. I wonder if there's a way to support both...

**Comment by juangon** [comment]
Yes, indeed, that would be nice having. Maybe we shouldn't hardcode the XA datasource class at all and just force users to set it through project-defaults.yml.

**Comment by Ladicek** [comment]
I have a solution that is backwards compatible, closing this PR. Thanks for the report and partial solution!

**Pull request closed without merging**
