### PR TITLE
SWARM-1172: add a fraction for integrate teiid product

### PR DESCRIPTION
**Pull request by kylinsoong**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
okay to test

**Comment by bobmcwhirter** [comment]
add to whitelist

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by kylinsoong** [comment]
@bobmcwhirter , from [1], Windows build has one failed, it looks
~~~
java.lang.AssertionError: <''> should be equal to :<'Management Interface'> ignoring case
	at org.wildfly.swarm.management.console.ManagementConsoleTest.testHomePageShouldHaveCorrectTitle(ManagementConsoleTest.java:47)
~~~
But, I don't think it caused by teiid fraction change, could you have a look, check whether this PR can be merged?

[1] https://ci.wildfly-swarm.io/job/wildfly-swarm-pull-request-windows/org.wildfly.swarm$testsuite-management-console/227/testReport/junit/org.wildfly.swarm.management.console/ManagementConsoleTest/testHomePageShouldHaveCorrectTitle/

**Comment by bobmcwhirter** [comment]
Retest this please

**Comment by bobmcwhirter** [comment]
CI lost its mind today. But may also be my bug. Asked CI to test again.

**Comment by kylinsoong** [comment]
@bobmcwhirter both linux and windows build success.

**Review by bobmcwhirter — APPROVED** [review]

**Pull request merged**
