### PR TITLE
THORN-2416: Remove Undertow MpJwtPrincipalHandler

### PR DESCRIPTION
**Pull request by sberyozkin**
See [THORN-2416](https://issues.jboss.org/browse/THORN-2416)

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Clearly there is a JIRA, so I wonder why it isn't mentioned in the commit messages, but LGTM otherwise :-)

**Comment by Ladicek** [comment]
Hmm, not sure about the MP RestClient TCK failures on Windows...

retest this please

**Comment by sberyozkin** [comment]
@Ladicek MP JWT is not involved in any way in the MP RestClient tests

**Comment by Ladicek** [comment]
I get that, but it's failing and I don't recall seeing those failures before :-)

**Comment by Ladicek** [comment]
Hmm, test failures are caused by empty test report files... Probably not a big deal.

**Comment by Ladicek** [comment]
Whoops, sorry for deleting your branch :-)

**Pull request merged**
