### PR TITLE
Further improvements:

### PR DESCRIPTION
**Pull request by bobmcwhirter**
- Removed the need for start=2 on numbered lists
- Replace # with = in all of the READMEs
- Added syntax-highlighting via coderay
- Added collapsible TOC via jquery
- Rev to latest fraction-plugin to get better hierarchic TOC.
- Added scm-publish to publish to docs.wildfly-swarm.io
  (hopefully works during `mvn deploy`)

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Output of the current PR can be seen here:

http://docs.wildfly-swarm.io/2017.11.0-SNAPSHOT/

**Review by kenfinnigan — DISMISSED** [review]

**Comment by bobmcwhirter** [comment]
Okay, @tradej -- ready for review.

Produced output is updated here: http://docs.wildfly-swarm.io/2017.11.0-SNAPSHOT/

**Comment by tradej** [comment]
Reviewing, will file a PR with suggestions.

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
Yay!

**Review by tradej — CHANGES_REQUESTED** [review]
[PR](https://github.com/bobmcwhirter/wildfly-swarm/pull/3) filed.

**Pull request merged**
