### PR TITLE
SWARM-1353 - Support @Configurable on EnhancedWhatnot.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Motivation
----------

We provide some helper configuration classes, such as InMemoryAuthentication,
which hang off enhanced classes, such as EnhancedSecurityRealm.

As we move away from main(), these become less useful from the YAML.

We should fix that.

Modifications
-------------
In addition to scrubbing around in the config-api for generated things, also
inspect @Configurable methods when added to our classes, and use them to configure
things through the EnhancedWhatnot classes.

Result
------
You can in-memory-(authentication|authorization) from YAML now with friendly ways
to configure them.

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
`testsuite-management` uses this.

**Comment by bobmcwhirter** [comment]
Yah, we'll be able to move to:

    swarm:
      management:
        security-realms:
          ManagementRealm:
            in-memory-authentication:
              users:
                bob:
                  password: TACOS!
        http-interface-management-interface:
          allowed-origin: http://localhost:8080
          security-realm: ManagementRealm

I'll update the testsuite and resync this PR.

**Comment by Ladicek** [comment]
Thank you!

**Comment by bobmcwhirter** [comment]
retest this please

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
