### PR TITLE
THORN-2031: Project rename

### PR DESCRIPTION
**Pull request by mkouba**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

This PR needs two more updates:
1. Upgrade to `io.thorntail:parent:10` (once released)
2. Upgrade to `io.thorntail:fraction-plugin:87` (once released)

### CODE REVIEW

**Comment by Ladicek** [comment]
The need to create artificial fraction classes looks suspicous. In my naive understanding, that shouldn't be necessary.

**Comment by mkouba** [comment]
@Ladicek I agree that this hack is not very nice. The problem is that we decided NOT to change package and module names (which is imho reasonable and could ease migration, etc.). However, when `wildfly-swarm-fraction-plugin` generates fraction manifest: if there is some java code and any class named `*Fraction` then its package is used to derive a module name (e.g. `org.wildfly.swarm.undertow`), otherwise `groupId` + `artifactId` is used for module name (e.g. `org.wildfly.swarm.container` before but `io.thorntail.container` after the change -> bang, the build crashes).

We can probably find a better solution but for now my goal was to make the build work with minimal changes. In other wors, we can always improve this later.

**Comment by Ladicek** [comment]
Aaaa gotcha! Thanks for explanation.

**Comment by kenfinnigan** [comment]
ok to test

**Comment by mkouba** [comment]
test this please

**Comment by mkouba** [comment]
test this please

**Comment by mkouba** [comment]
test this please

**Comment by kenfinnigan** [comment]
retest this please

**Comment by mkouba** [comment]
@kenfinnigan This PR is ready for final review/merge.

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
