### PR TITLE
[THORN-2251] MicroProfile Fault Tolerance 2.0 + SmallRye Fault Tolerance 2.0.1

### PR DESCRIPTION
**Pull request by Ladicek**
- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

### CODE REVIEW

**Comment by Ladicek** [comment]
This isn't ready yet, because SmallRye Fault Tolerance 2.0 hasn't been released yet, but there's a PR (https://github.com/smallrye/smallrye-fault-tolerance/pull/62) that is complete and should be merged soon. So I'm submitting this for a preliminary review.

**Comment by Ladicek** [comment]
Windows failure is due to full disk, will check tomorrow.

**Comment by Ladicek** [comment]
Updated to SmallRye FT 2.0.1 to fix a RestClient integration bug.

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by Ladicek** [comment]
It seems the CI died for a bit and had to be restarted. Or something like that, the Windows build apparently didn't finish.

retest this please

**Pull request merged**
