### PR TITLE
[SWARM-804] Enhance Zipkin fraction to accept a service name

### PR DESCRIPTION
**Pull request by jamesnetherton**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

---

https://issues.jboss.org/browse/SWARM-804

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Review by gastaldi — COMMENTED** [review]
Maybe it would be nice to have the service name always set, to avoid seeing it as _unknown_

**Comment by gastaldi** [comment]
Of course, that should not prevent this PR from being merged.

**Comment by jamesnetherton** [comment]
Is this ok be merged? Unlikely I'll get time this week (or next) to make the additional enhancement suggested above.

**Comment by gastaldi** [comment]
Yes, sorry it took so long. Thanks

**Pull request merged**
