### PR TITLE
SWARM-1634: MP Config module.conf duplicate modules

### PR DESCRIPTION
**Pull request by kenfinnigan**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------
Two module entries in module.conf

Modifications
-------------
Removed duplicate module in module.conf

Also fixed artifact being returned from package detector.

Result
------
No impact on product.

### CODE REVIEW

**Review by heiko-braun — APPROVED** [review]

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
test this please

**Comment by bobmcwhirter** [comment]
retest this please

**Pull request merged**
