### PR TITLE
THORN-2259: SmallRye Open Tracing 1.3

### PR DESCRIPTION
**Pull request by kenfinnigan**
- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------
Update to SmallRye Open Tracing 1.3

Modifications
-------------
Updated versions for SmallRye Open Tracing.

Result
------
Uses SmallRye Open Tracing 1.3

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I would have expected OpenTracing and Jaeger updates too. Do we know if we want to do that?

**Comment by kenfinnigan** [comment]
It updated the `opentracing-jaxrs` version, but @pavolloffay said that's all that was required

**Comment by kenfinnigan** [comment]
retest this please

**Comment by pavolloffay** [comment]
The OpenTracing API version stays the same so we don't have to update Jaeger either.

**Pull request merged**
