### PR TITLE
SWARM-1714: Upgrading the Teiid fraction to use WF 11

### PR DESCRIPTION
**Pull request by rareddy**
- [ x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
add to whitelist

**Comment by rareddy** [comment]
@kenfinnigan What is needed on this to move forward? I do not think I understand what checks that are failed?

**Comment by kenfinnigan** [comment]
tbh I don't know as I think the CI job log may have rolled off, as it doesn't seem to want to load.

There's a bunch of Eclipse MP related PRs that are going through right now, once they're in I will retest this PR and we can see where we stand

**Comment by kenfinnigan** [comment]
test this please

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
