### PR TITLE
Upgrade to WildFly-Camel-4.8.0

### PR DESCRIPTION
**Pull request by tdiesler**
- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Why the need to make the maven enforcer rule empty?

**Comment by bobmcwhirter** [comment]
I know camel would routinely violate the rule if tests failed. It doesn't clean up itself very well. I think we should fix camel not disable the rule.

**Comment by tdiesler** [comment]
Unfortunately, I don't know what to do with these rules or what they even are. It also seems that these rules were introduced in previous releases regardless of breaking the camel tests in the process. 

Perhaps we can start by explaining what these rules are for and then talk about what can be done for the camel integration

**Comment by kenfinnigan** [comment]
@tdiesler, basically the rules ensure that fractions clean up after themselves.

Whether that be temp space or other erroneous files that a test might create.

**Comment by kenfinnigan** [comment]
Closing this

**Pull request closed without merging**
