### PR TITLE
Update to parent version 9

### PR DESCRIPTION
**Pull request by kenfinnigan**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by gastaldi — DISMISSED** [review]

**Comment by Ladicek** [comment]
A couple of days ago, we changed one of the `testsuite` modules to also refer directly to the Swarm parent. This commit should change that too?

EDIT: ayea, it was the `testsuite-jaxrs-client` module.

**Comment by kenfinnigan** [comment]
Updated, please review

**Comment by Ladicek** [comment]
@gastaldi see https://github.com/wildfly-swarm/wildfly-swarm/pull/538 :-)

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
