### PR TITLE
[THORN-2171] Remove health-api as dependency

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`? --> No, build fails for some other reason

Fix https://issues.jboss.org/browse/THORN-2171

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
I wonder why does MP Health even have a dependency on `health-api`. It belongs to the old `monitor` fraction which is deprecated.

**Comment by ruromero** [comment]
@Ladicek I should have used @org.eclipse.microprofile.health.Health

**Comment by ruromero** [comment]
Anyhow, as you just said, microprofile-health  depends on health-api, I don't know if this is correct.

**Comment by Ladicek** [comment]
Yea I think that's an actual bug.

**Comment by ruromero** [comment]
@Ladicek updated commit accordingly

**Comment by kenfinnigan** [comment]
ok to test

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Windows failures (MP Config TCK) are unrelated.

**Comment by sberyozkin** [comment]
I've kept this dependency because the microprofile-health fraction still supports the legacy annotations, it checks the names of those annotations. That code has to be removed as well if it is not needed

**Comment by Ladicek** [comment]
Interesting, I had no idea our implementation of MP Health still supports the old `monitor` stuff. It doesn't make much sense to me.

**Comment by Ladicek** [comment]
Looking at the code and the only thing our impl of MP Health does is that it allows `@org.wildfly.swarm.health.Health` instead of `@org.eclipse.microprofile.health.inject.Health`, that's all. I wonder how many users use the old annotation with MP Health -- I suspect it's zero so we don't have to care.

And given how the code refers to the old annotation (it's just a Jandex lookup, nothing else), this could only be a compile-time breakage, which can be fixed by adding the dependency on `health-api` explicitly.

**Pull request merged**
