### PR TITLE
ENTSWM-258: switched to fraction plugin 80

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
retest this please

**Comment by michalszynkiewicz** [comment]
retest this please

**Comment by michalszynkiewicz** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Comment by michalszynkiewicz** [comment]
restest this please

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
