### PR TITLE
SWARM-1693 [REV-2] - Microprofile + OpenAPI 1.0.1 spec implementation (fraction)

### PR DESCRIPTION
**Pull request by EricWittmann**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`? **really this time**

-----

### CODE REVIEW

**Comment by juangon** [comment]
Ok it failed on Linux here too.

Will send a PR to see how it goes on Monday

**Comment by juangon** [comment]
Hi @EricWittmann I've sent you a possible fix for this: https://github.com/EricWittmann/wildfly-swarm/pull/2 . Can you check if it's enough?

Thanks!

**Comment by EricWittmann** [comment]
I'll test it locally certainly.  But note that the build has never failed for me locally the way it has on CI and for others (e.g. @msavy ).  So if it passes my local build shall I push it to the PR branch so it can be tested on CI?

**Comment by juangon** [comment]
Hi @EricWittmann . Yes please, as that is the failing environment. If it passes, maybe I should make the PR properly with a right SWARM JIRA ticket.

**Comment by EricWittmann** [comment]
OK everything worked locally.  I have pushed the commit to the PR branch.  Should be retesting now.

**Comment by juangon** [comment]
Ok @EricWittmann fingers crossed

**Comment by juangon** [comment]
Oh it fails on windows...

**Comment by kenfinnigan** [comment]
@EricWittmann, can https://github.com/wildfly-swarm/wildfly-swarm/pull/810 be closed as out of date?

@juangon, @mkouba, @michalszynkiewicz, @sberyozkin, @heiko-braun - I want this reviewed by a couple of people Tuesday morning, as it's lots of code, so that we can put it to bed and do the 2018.3.1 release to include it.

We can always revisit the Windows temp file issue later

**Comment by juangon** [comment]
@kenfinnigan will try to reproduce locally on Windows. If can't find a fix, I can send a PR for disabling temp file check for this test also

**Comment by mkouba** [comment]
@juangon Hm, this time it failed in `arquillian-test` and not in OpenAPI TCK. 

@kenfinnigan I already spent some time with this PR and I think it's good to go.

**Comment by juangon** [comment]
So this is getting interesting. I could reproduce the failure on Windows, but after some attempts couldn't make it work (file is still locked by Windows at that time). 

And then I returned to the original failure in openapi TCK without my suggested fix. And in my windows env it works!! Maybe we should re-run CI tests for the original PR

**Comment by EricWittmann** [comment]
@kenfinnigan Yes 810 is out of date.  This one supersedes it.  So other than @juangon's suggestion to retest #810 I can think of no reason not to close it.

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
