### PR TITLE
fix(THORN-2049): proper handling of --file flag for maven builds

### PR DESCRIPTION
**Pull request by bartoszmajsak**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

* This PR fixes how Maven builds are handlend using `-f|--file` by creating `FileSystemLayout` pointing to proper path.
* Extracted Maven specific logic out of `FileSystemLayout` to `MavenBuildFileResolver` and tested in isolation
 
Few observations which I could take care of in this or seperated PR

* We are using old and not longer maintained `fest-assert` library. I can not only bump it to lastest `assertj` (a successor), but convert standard JUnit assertions to them
* I introduced [system-rules](https://stefanbirkner.github.io/system-rules/) JUnit library to control `MAVEN_CMD_LINE_ARGS` while testing `MavenBuildFileResolver`. I can make it configured in the root pom to be used across all the modules

Relates to https://github.com/openshiftio/openshift.io/issues/2152

### CODE REVIEW

**Comment by kenfinnigan** [comment]
ok to test

**Comment by bartoszmajsak** [comment]
@kenfinnigan I ran `mvn clean install` on top of latest master with my changes from this PR and all is good on my side. Any idea what could be the cause of

```
org.jboss.arquillian.container.spi.client.container.DeploymentException: Connection refused (Connection refused)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```
in `org.eclipse.microprofile.rest.client.tck.AdditionalRegistrationTest`?


Proof ;)

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53:08 min
[INFO] Finished at: 2018-07-30T12:25:16+02:00
[INFO] Final Memory: 1264M/8225M
````

**Comment by kenfinnigan** [comment]
@bartoszmajsak, by default the MP TCKs don't run as part of regular build, which is why it likely didn't fail for you.

Need to add `-P microprofile-tck` to run the TCKs.

https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/AdditionalRegistrationTest.java is the test that fails

**Comment by bartoszmajsak** [comment]
@kenfinnigan Ok, thanks. Didn't know these are disabled and somehow missed that on the long list of modules :) I will investigate.

**Comment by juangon** [comment]
retest this please

**Comment by bartoszmajsak** [comment]
@juangon the TCK test is still broken. I will have a look tomorrow and see if I can fix that.

**Comment by juangon** [comment]
Hi @bartoszmajsak how is the TCK fix going? I will put this PR on hold in the meantime.

**Comment by bartoszmajsak** [comment]
@juangon sure, I will continue investigation this week and come back to you.

**Comment by manovotn** [comment]
@bartoszmajsak have you managed to take a look at this?
If you lack time, I can try and glance at it (although I have no idea what it's about :))

**Comment by mustaphazorgati** [comment]
Hey guys!
What's the status for this PR? We'd love to use the `-f` option for maven. 
Can I somehow help?

**Comment by Ladicek** [comment]
This PR should be closed, as it's very much out of date, has merge conflicts, and tests were failing last time the code was updated. If someone wants to take a stab at this, another PR would be very much welcome!

**Pull request closed without merging**
