### PR TITLE
THORN-2356: @ClientHeaderParam in rest-client:1.2

### PR DESCRIPTION
**Pull request by penehyba**
- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
Please transition the JIRA through the workflow, too.

**Comment by Ladicek** [comment]
retest this please

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by sberyozkin** [comment]
The Linux failure is caused by:
```
Caused by: java.lang.NullPointerException
	at io.smallrye.metrics.MetricsRegistryImpl.getMetrics(MetricsRegistryImpl.java:342)
```
Does it ring any bells ?
In meantime I'm merging this PR

**Comment by Ladicek** [comment]
Hmm, probably a failure in SmallRye Fault Tolerance (or SmallRye Metrics, but I'd say it's probably FT).

**Pull request merged**
