### PR TITLE
SWARM-1420: Add dependencies that don't get aligned to bom-dependency

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
Motivation
----------
Enable prod alignment of the affected dependencies

Modifications
-------------
The affected dependencies have been added to bom-dependency/pom.xml
Additionally, org.apache.httpcomponents:httpclient has been downgraded to 4.5.0 (from 4.5.2)
and its version has been moved to the parent pom

Result
------
All the dependencies of the prod build are now aligned.

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
Not sure, but if you want to pin the dependency on `org.apache.httpcomponents:httpclient`, you'll probably also want to pin the dependency on `org.apache.httpcomponents:fluent-hc` (to the same version number). It's used in a bunch of modules of the test suite.

**Comment by michalszynkiewicz** [comment]
@Ladicek Done

**Review by Ladicek — DISMISSED** [review]

**Review by bobmcwhirter — DISMISSED** [review]

**Review by Ladicek — DISMISSED** [review]

**Review by Ladicek — APPROVED** [review]

**Comment by kenfinnigan** [comment]
Based on what the changes involve, are we aligning testsuite dependencies?

To me that seems unnecessary

**Comment by Ladicek** [comment]
I think it's because PME modifies the testsuite modules as well. I briefly talked to @michalszynkiewicz if it would be possible to skip the testsuite modules when doing dependency alignment, he even did some experiments, but I don't know the final results.

**Comment by michalszynkiewicz** [comment]
yes, I tried to exclude testsuite, but PME goes through everything...
And it was failing with having two versions of the same library (it caused a conflict in alignment)

**Comment by kenfinnigan** [comment]
Doesn't that seem like a bug that PME can't "ignore" certain things?

It's a waste of time for us to "align" things that aren't even required for a user building their project

**Pull request merged**
