### PR TITLE
ENTSWM-211 Added module dependencies in order to avoid possible ClassNotFound exceptions

### PR DESCRIPTION
**Pull request by juangon**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Have you rebuilt locally and this solves your issue?

In the future it would be preferred if we could create a corresponding SWARM JIRA for the PR, and also assign the issue to yourself to let others know you're working on it. Thanks

**Comment by juangon** [comment]
@bobmcwhirter @kenfinnigan must confess I have not many idea about jboss modules but this works fine and seems to be minimal changes to make it work. /cc @Ladicek

**Comment by Ladicek** [comment]
Agreed about the SWARM jira.

**Comment by juangon** [comment]
Oh ok @kenfinnigan as I saw ENTSWM commits here I thought it was normal behavior. And yes, I checked it works for this issue.

**Review by bobmcwhirter — APPROVED** [review]

**Pull request merged**
