### PR TITLE
Minimalism changes in the docs

### PR DESCRIPTION
**Pull request by tradej**
Resolves RHOARDOC-1404

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]
There should be a JIRA, but LGTM anyway :-)

**Comment by tradej** [comment]
@Ladicek Do I take it I should have a THORN and ENTSWM JIRA for every RHOARDOC I fix? Isn't that quite a bit of red tape?

**Comment by Ladicek** [comment]
Ah I didn't notice the RHOARDOC mention in the comment, I'm used to commit messages in the form of "[JIRA] message". Sure, probably OK like this.

**Comment by tradej** [comment]
I see, I'll start doing that.

**Comment by juangon** [comment]
@Ladicek I don't have merge permissions myself. Can you please merge it if still ready for it? Thanks!

**Pull request merged**
