### PR TITLE
Renamed .gitignore files to .gitkeep

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
What's the reason for rename?

**Comment by gastaldi** [comment]
That's usually the convention for having empty directories. .gitignore is normally used only in the project root

**Comment by gastaldi** [comment]
This explains better: http://harmssite.com/2012/08/gitignore-vs-gitkeep/

**Comment by kenfinnigan** [comment]
Do we even need the empty directories?

Why not remove them?

**Comment by bobmcwhirter** [comment]
They are retained for hbrauns parser factory stuff.

## 

Sent from my iPhone

On Mar 16, 2016, at 7:34 PM, Ken Finnigan notifications@github.com wrote:

Do we even need the empty directories?

Why not remove them?

**Pull request merged**
