### PR TITLE
THORN-2156: Decrypt JWE based on content in header.

### PR DESCRIPTION
**Pull request by dvddhln**
Motivation
----------
The purpose of this commit is to allow for several key aliases for signing, verification, encryption and decryption.

Modifications
-------------
Add new configuration properties, along with new configuration logic and tests.

Result
------
The commit should be backwards compatible and not break anything.

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi David, thanks very much for this effort.
It looks good, I'd suggest few minor modifications:
* The defaulting to the signature.keyAlias should be done IMHO inside prepareSignatureVerficaitionProperties (in.alias or out.alias are always more specific, catch all is just .alias) as opposed to defaulting the signature.keyAlias to the signature.keyOutAlias, etc, inside the JoseConfiguration getters, as it is not consistent with the setters (and same for the encryption/decryption).  
* The new test is good, but please try to to use the Jose.decryption() to check the kids as I did earlier to verify the right key was selected :-)

Cheers, Sergey

**Comment by dvddhln** [comment]
Thanks for the feedback Sergey, I have added the modifications as suggested.

**Comment by sberyozkin** [comment]
Thanks David. 
There is one more cosmetic change that I'd like to propose, about the attribute docs.
I'd like to propose to update the existing 'encryptionKeyAlias' docs to the format you have introduced in this PR to reflect a bit better its default status, to something like "Key Alias in the keystore to be used for the encryption or decryption" (may be add 'by default' as well) and then slightly update the new docs, from "Encryption Key Alias in the keystore to be used for the encryption" to "Key Alias in the keystore to be used for the encryption only" and similarly for the decryption case; and the same for the signature/verification - the new docs refer to the encryption/decryption there :-)
And finally, re the test, have a look here:

https://github.com/thorntail/thorntail/blob/master/testsuite/testsuite-jose/src/test/java/org/wildfly/swarm/jaxrs/JoseCompactTest.java#L100

Can you please update the client code to check the 'kid' is 2 ? (I don't think there is a way to check which key was used for the decryption yet, may be we can introduce some listeners in time which can have the details like key alias, etc, reported, but it can be done in the future :-)). And the 'testJweEncryptDecryption()' can be dropped there because it only confirms the produced sequence is correct JWE and it is already tested in the other test suite - but it is fine if you prefer to keep it

Thanks

**Comment by dvddhln** [comment]
Yes, sorry about that :-) Should be fixed now!

**Comment by sberyozkin** [comment]
Np, thanks, all LGTM now

**Comment by sberyozkin** [comment]
By the way, I hope JoseOperation can be used for other purposes as well, such as helping the future pluggable key store resolvers to find the right key as well, etc...

**Review by sberyozkin — DISMISSED** [review]

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
Hi David, sorry, forgot one more thing.
If you can find some time, can you please tweak a bit this code too:
https://github.com/thorntail/thorntail/blob/master/testsuite/testsuite-jose-jose4j/src/main/java/org/wildfly/swarm/jose/jose4j/Jose4jJoseImpl.java
(I guess one just needs to replace something like config.encryptionKeyAlias() with encryptionKeyAlias() - as you did in in the default impl, etc) and then just copy the same test there as well.
Not  a blocker for this PR, I can do in a few weeks as well 

thanks

**Comment by dvddhln** [comment]
No worries Sergey,
I added the required modificaitons along with the case for the signatureAlias() aswell.

**Comment by sberyozkin** [comment]
Great, thanks for the super fast PR update, just a couple of minor updates are still needed - ex, in case of the encryption - when it is 'jwk' or 'boolean encryption == false' (may be replace this boolean with JoseOperation) - decryptionAlias() (same code as in the default impl) should be used, same for the signature case. It is nearly done :-)

**Comment by dvddhln** [comment]
Yes, you are right,  just commited the changes :-)

**Comment by sberyozkin** [comment]
All looks awesome now :-)

**Review by sberyozkin — DISMISSED** [review]

**Comment by michalszynkiewicz** [comment]
retest this please

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
retest this please

**Review by sberyozkin — DISMISSED** [review]

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
I may end up testing it locally and if I can confirm it is passing then I'll merge

**Comment by dvddhln** [comment]
Cheers Sergey, any idea on why the build is not starting?

**Comment by sberyozkin** [comment]
Hi David, not sure yet, might be a communication issue with the CI server

**Comment by sberyozkin** [comment]
David, can you please try to pull the latest master into your branch, using '--rebase' and then do a forced push ? May be that will trigger it, the forced push helped with the other PR

**Comment by sberyozkin** [comment]
I'm afraid it did not help. I'll proceed with the local verification asap, looks like this PR keeps some old state which blocks it from communicating with Jenkins

**Comment by sberyozkin** [comment]
retest this please

**Review by sberyozkin — DISMISSED** [review]

**Comment by sberyozkin** [comment]
Hi David, I'm sorry, looks like your latest update picked up the extra changes. I meant that you'd rebase this PR branch against the up-to-date master of the forked Thorntail repo. So your last push to the PR branch needs be reverted. Please revert  so that only JOSE related changes are in and I promise it will be the last update I've asked you to do :-), I'll validate locally and merge as the admin. Once again, sorry about it.

**Comment by sberyozkin** [comment]
Though may be it won't be a problem, I'll ping if I have any issues with merging...

**Comment by dvddhln** [comment]
No worries, sorry about messing up the commits, perhaps should have stick to just one commit. :)

**Comment by sberyozkin** [comment]
I confirm the test have passed for me locally, thanks David

**Review by sberyozkin — APPROVED** [review]

**Pull request merged**
