### PR TITLE
SWARM-437 - Allow annotations to advertise services.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

---
## Motivation

In the case a person doesn't use a main(), and wants to perform
multiple advertisements, particularly those not based on the simplified
archive name, provide an @Advertise annotation.
## Modifications

@Annotation is inspected for each archive, and can specify the
name of services to advertise.  It is a repeatable annotation
and several can be applied to any class, for whatever reason.
## Result

@Advertise("tacos")
public class Tacos { ... }

Will cause the same behaviour as calling

  archive.as(TopologyArchive.class).advertise("tacos")

on the deployed archive containing the aforementioned class.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
Looks good to me

**Comment by kenfinnigan** [comment]
Does this impact an archive without annotations or .advertise() calls such that presence of topology by default will advertise a service based on name of artifact?

Don't think it does from quick look at code, but wanted to check

**Comment by bobmcwhirter** [comment]
@kenfinnigan you bring up a good point.

Currently, we do the full list of ArchivePreparers, which will auto-advertise.

Then, we do the full list of MetadataProcessors, which detect these annotations.

I'm trying a local build which swaps the direction of those.  Metadata first, then general ArchivePreparers.

Plus, trying to convince CI to be less goofy.

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Pull request merged**
