### PR TITLE
SWARM-1222: Fix security web xml detector, add security fraction detection tests and cleanup API.

### PR DESCRIPTION
**Pull request by juangon**
Motivation
----------
The initial motivation of this commit was adding test for security detection. After doing it, it was noticeable that security web.xml detector wasn't working, so another fix was needed.

Modifications
-------------
After fixing security detector, other bug arised, because shrinkwrap utility class for parsing web.xml (Descriptors) was closing the stream, which caused error when a second webxml fraction detector was executed (for example, JSFServletDetector and SecurityWebXmlDetector). In order to fix that, some steps had been taken:

1-Unify under FileSource (renamed to PathSource to make more consistent to their new inherit classes), now one more method had been added to make easier obtaining InputStream. PathSource has 2 inherit classes: FilePathSource (equivalent to previous FileSource) and ZipPathSource.
2-Thanks to previous unification, delegate InputStream obtaining to Scanner or Detector classes.
3-In order to make classes just doing a single purpose ("Separation of concerns"), code for traversing files, directories and zip entries from Scanner had been moved to FractionUsageAnalyzer. This made possible removing many code from Scanner class. So now FractionUsageAnalyzer just does File/zip traversing, executing other methods, then delegate simple source scan to Scanner.
4-Now that FileSource (named PathSource) has everything we want, unify all methods to just accept PathSource instead of the previous ones (InputStream, String ,etc).

Result
------
Now SecuredWebXMLDetector is working, and API in detectors and Scanners seems more consistent and unified.

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

Hi @bobmcwhirter @Ladicek. Thanks very much Ladislav for your pull! I didn't know this JDK 8 feature. I could make Ladislav's example pull (https://github.com/Ladicek/wildfly-swarm/tree/stop-passing-around-inputstreams) work with some additional change. But after reading it, and after previous knowledge, it made me feel this API needed a change, and some classes (FractionUsageAnalyzer Scanner) looked a bit confusing to me.

So, I used previous existent FileSource class to make something equivalent to what Ladislav made in his pull with InputStreamSupplier, but using this class could make API more unified and could remove some confusing methods that in the end made everything looked like duplicated.

So, in the end I think API now looks cleaner, unified, and FractionUsageAnalyzer and Scanner just does 1 single purpose (FractionUsageAnalyzer traverses through directories and zip files and Scanner now doesn't traverse those and just scan 1 single source).

Hope it makes sense and didn't break anything!

Thanks!

### CODE REVIEW

**Comment by Ladicek** [comment]
Did you possibly want to delete `WebXmlDescriptorFractionDetector` like you did in the previous PR?

**Comment by juangon** [comment]
Sure @Ladicek! Thanks for pointing out. Gonna change that tomorrow, although CI failure for Windows doesn't make sense to me and seems unrelated.

**Comment by Ladicek** [comment]
Indeed the CI failure looks unrelated.

**Comment by Ladicek** [comment]
Otherwise LGTM. I think this makes the fraction detection code a bit easier to understand, but that doesn't mean I finally understand it :-)

**Comment by bobmcwhirter** [comment]
Does this supercede #509 ?  If so, could you close that one?

**Comment by juangon** [comment]
Please @bobmcwhirter wait for tomorrow, gonna remove that class I forgot. Rest of code seems ok.

**Review by kenfinnigan — APPROVED** [review]

**Comment by juangon** [comment]
I've removed that pending class, and seems all tests passes. /cc @bobmcwhirter @kenfinnigan @Ladicek

**Comment by Ladicek** [comment]
+1 from me.

**Pull request merged**
