### PR TITLE
[THORN-2294] update to Keycloak 4.8.1.Final

### PR DESCRIPTION
**Pull request by Ladicek**
- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

Keycloak Config API didn't hit Central yet, but should be there pretty soon.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
retest this please

**Comment by Ladicek** [comment]
It's there, yay :-)

**Comment by Ladicek** [comment]
Please hold, there's Keycloak 4.8.2.Final and 4.8.3.Final is a possibility too. I'll keep the Keycloak Config API updated, but would prefer this PR to remain open.

**Comment by Ladicek** [comment]
OK, so maybe we should merge this, to stay as up-to-date as possible, and decide again when the last 4.8.x release comes (e.g. update to it in a point release).

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
