### PR TITLE
SWARM-1909: Swagger: Default the context root to JAX-RS context root

### PR DESCRIPTION
**Pull request by roguexz**
Motivation
----------
Based on discussions in SWARM-1667, it made sense to set the defaults for Swagger resources to be made available under the JAX-RS Application context path.

Modifications
-------------
* Look at the IndexView of the archive and determine the JAX-RS Application path.
* If the developer has not defined "swarm.deployment.*.swagger.root", then use the above path.
* Updated test case.

Result
------
Verified the functionality.

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by roguexz** [comment]
retest me please.

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by roguexz** [comment]
What's up with the CI? :)

**Comment by bobmcwhirter** [comment]
Retest this please

**Comment by bobmcwhirter** [comment]
Dunno. We need CI for our CI.

**Comment by roguexz** [comment]
Retest this please

**Comment by roguexz** [comment]
Was the Jenkins instance recently upgraded to the latest LTS?

> Caused by: java.lang.UnsupportedOperationException: Refusing to marshal org.kohsuke.github.GHUser for security reasons; see https://jenkins.io/redirect/class-filter/

Might be related to [JENKINS-48950](https://issues.jenkins-ci.org/browse/JENKINS-48950). Can the maintainers of the CI please have a look at the issue?

**Comment by Ladicek** [comment]
Indeed that seems to be the case. We'll likely have to update a couple of Jenkins plugins.

**Comment by kenfinnigan** [comment]
retest this please

**Comment by roguexz** [comment]
I would prefer that this be merged after #844 & #849 ... this PR will need a rebase after those get merged.

**Comment by roguexz** [comment]
@kenfinnigan I have updated the content of [SWARM-1909](https://issues.jboss.org/browse/SWARM-1909) to reflect the actual intent of this change. Can you please review it and let me know if it makes sense to have this feature?

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
