### PR TITLE
THORN-2122: add a HowTo for metrics with MP Metrics and Prometheus

### PR DESCRIPTION
**Pull request by Ladicek**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
CC @tradej @jclingan

**Comment by kenfinnigan** [comment]
Is it worth explicitly mentioning that the metrics are exposed from the app on http://localhost:8080/metrics which is what Prometheus consumes?

**Comment by Ladicek** [comment]
Good point @kenfinnigan!

**Comment by Ladicek** [comment]
Fixed.

**Review by kenfinnigan — DISMISSED** [review]

**Review by tradej — CHANGES_REQUESTED** [review]
PR with changes submitted at Ladicek#2.

**Comment by Ladicek** [comment]
I've merged @tradej's PR, so the changes are now present in this PR.

**Review by tradej — DISMISSED** [review]

**Review by manovotn — DISMISSED** [review]

**Comment by Ladicek** [comment]
Rebased and resolved conflicts.

**Review by manovotn — APPROVED** [review]

**Review by tradej — APPROVED** [review]

**Pull request merged**
