### PR TITLE
SWARM-688 don't list all fractions in info log.

### PR DESCRIPTION
**Pull request by tremes**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

---
## Motivation

Currently all fractions are output at the startup of the container in the log.
## Modifications

Log list of fractions under DEBUG level
## Result

List of fractions is logged/available under DEBUG level only

### CODE REVIEW

**Comment by kenfinnigan** [comment]
@tremes the issue linked to wasn't so much about logging all the fractions as DEBUG, but logging the fractions that are internal as DEBUG.

Apologies if the JIRA wasn't clear

**Comment by tremes** [comment]
Ah ok..will update

**Comment by kenfinnigan** [comment]
Thanks!

**Comment by bobmcwhirter** [comment]
09:18 bobmcw: tremes: so, I think if there's not an internal flag on fraction-manifest.yml, you can tell it's an internal fraction (maybe) by lack of a bootstrap-module or other key typically present
09:18 bobmcw: at least that'd catch the module-only fractions that don't have a matching FooFraction class
09:18 bobmcw: but not so much things like :ee or :io
09:19 bobmcw: if you need another flag to denote which fractions are internal, then wildfly-swarm-fraction-plugin can be modified
09:19 bobmcw: so that it adds it to fraction-manifest.yaml

**Comment by tremes** [comment]
I think we can leave it as it is and close this because fractions like `jaxrs-jsonp`, `jaxrs-cdi`, etc are not listed anyway. 

If I understand it correctly we load fraction manifests only for bootstrap-modules in `ApplicationEnvironment#loadFractionManifestsFromUberjar` and e.g `jaxrs-jsonp` is not in bootstrap-modules because its manifest doesn't have any `module` attribute (checked in `DependencyManager#analyzeFractionManifests`). Question aside: Is that intended?

Please correct me if I am wrong.

**Pull request closed without merging**
