### PR TITLE
SWARM-1632: Part 2, Change JWT packages to org.wildfly.swarm.microprofile.jwtauth

### PR DESCRIPTION
**Pull request by heiko-braun**
This PR also enables the JWT TCK

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Does this PR need to rebased onto master once https://github.com/wildfly-swarm/wildfly-swarm/pull/708 is merged?

It seems like there's a lot of files being changed in the PR that are part of other changes

**Comment by heiko-braun** [comment]
It builds on #708 . So if we merge that first we should be fine I guess

**Comment by kenfinnigan** [comment]
@heiko-braun looks like in merging #708 this needs to be fixed because of conflicts

**Comment by heiko-braun** [comment]
I'll rebase this

**Comment by kenfinnigan** [comment]
thanks

**Comment by heiko-braun** [comment]
Superseded by #713

**Pull request closed without merging**
