### PR TITLE
SWARM-1392: Upgrade Swagger and Swagger-UI

### PR DESCRIPTION
**Pull request by kevcodez**
[SWARM-1392](https://issues.jboss.org/browse/SWARM-1392): Upgrade Swagger and Swagger-UI.

Motivation
----------
Upgrade Swagger and Swagger-UI to latest stable versions. Swagger-UI has a
new major version.

Modifications
-------------
build-parent pom.xml has been modified to hold the new versions.

Result
------
Latest Swagger-Version and the newest stable swagger-ui, based on React,
will be used.

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Okay to test

**Comment by kenfinnigan** [comment]
Have you manually verified this change is sufficient to update swagger fractions to new version in a small app?

Not sure how thorough the testsuite we have for swagger is

**Comment by kevcodez** [comment]
@kenfinnigan The Swagger-UI 3.x supports OpenApi Spec 2.0 and above. Upgrading Swagger-UI drops support for OpenApi Spec 1.x. This should work out-of-the-box. However, I will do some further testing, to make sure this is working.

I will setup a simple WildFly swarm app with jax-rs+swagger and I will test the swagger-ui standalone-server. Anything else to test?

**Comment by kenfinnigan** [comment]
That would be awesome, thanks @kevcodez

**Comment by kevcodez** [comment]
@kenfinnigan Tested with standalone server and integrated with Jax-RS, works fine. If there is anything else I can test, let me know

**Review by kenfinnigan — APPROVED** [review]
Thanks for the extra testing!

**Comment by kevcodez** [comment]
@kenfinnigan Sure, no problem :)

Just for clarification - can you assign the JIRA issue to me (User kgrueneberg)?

What is the best way to be assigned an unassigned ticket? Leave a comment on Jira/Github?

**Comment by kenfinnigan** [comment]
Was going to do that, but your GH handle is different, so I couldn't find you. All updated now.

Either on the JIRA, asking to be assigned it, or when a PR is submitted and a comment with JIRA id

**Pull request merged**
