### PR TITLE
Simple keycloak test v4

### LINKED ISSUE #1008: Make simple keycloak test verify KC adapter is blocking the unsecure requests

### PR DESCRIPTION
**Pull request by sberyozkin**
KC adapter hangs waiting if no KC server is available and throws NPE if it finds no deployment so the test checks it is 500. (I'm following on it on the KC users list)

Resolves #1008

### CODE REVIEW

**Comment by sberyozkin** [comment]
The docker test will test against the KC server

**Comment by sberyozkin** [comment]
retest this please

**Comment by kenfinnigan** [comment]
The failure details are:

    test(io.thorntail.testsuite.security.keycloak.KeycloakAppTest)  Time elapsed: 1.011 sec  <<< FAILURE!
    java.lang.AssertionError: 
    1 expectation failed.
    Expected status code <500> but was <200>.

	at io.thorntail.testsuite.security.keycloak.KeycloakAppTest.test(KeycloakAppTest.java:17)

**Comment by sberyozkin** [comment]
Hmm, I thought I got it passing, let me check...

**Comment by sberyozkin** [comment]
Hi Ken, it is passing for me... can you please give me a favour and follow the cmd-line instructions (Step1) and see if it passes for you ?

**Comment by sberyozkin** [comment]
Just rerun the test (removing few lines for brewity, note KC NPE this is when a request to /secured leads ConfigResolver returning null), see the attached file:

[simple-kc-test.txt](https://github.com/thorntail/thorntail/files/2127367/simple-kc-test.txt)

That is why I was wondering, if the CI build test failure can be linked somehow to the build setup (which points to some other Thorntail v4 issue yet unknown); if you will see the test passing locally too then it will narrow it down a bit

**Comment by sberyozkin** [comment]
[simple-kc-test.txt](https://github.com/thorntail/thorntail/files/2127367/simple-kc-test.txt)

**Comment by sberyozkin** [comment]
Got the difference. In the build it is:

WARN  : Thu Jun 21 15:47:42 UTC 2018 [org.keycloak.adapters.undertow.KeycloakServletExtension] No adapter configuration.  Keycloak is unconfigured and will deny all requests.

and in my test:

INFO  : Fri Jun 22 11:56:54 IST 2018 [org.keycloak.adapters.undertow.KeycloakServletExtension] Using io.thorntail.security.keycloak.impl.ConfigResolver to resolve Keycloak configuration

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
Ken, please add me to whitelist

**Comment by sberyozkin** [comment]
Small progress, in CI build Thorntail KeycloakDeploymentCustomizer is not loaded (or deployments are not injected - investigating next...), with the log  message I see in my local build:
--> @org.eclipse.microprofile.auth.LoginConfig(realmName=, authMethod=KEYCLOAK)
INFO  : Fri Jun 22 12:53:29 IST 2018 [io.thorntail.security.keycloak] THORN-012001: Adding KeycloakConfigResolver to the deployment jaxrs-MyJaxrsApplication
INFO  : Fri Jun 22 12:53:29 IST 2018 [io.thorntail.kernel] THORN-000013: phase [initialize] completed in 0.10s

while CI build only reports that LoginConfig annotation has been found

**Comment by sberyozkin** [comment]
Right, the problem is elsewhere, with the KeycloakDeploymentCustomizer logging:
INFO  : Fri Jun 22 12:34:18 UTC 2018 [io.thorntail.security.keycloak] THORN-012003: Deployment customization
INFO  : Fri Jun 22 12:34:18 UTC 2018 [io.thorntail.security.keycloak] THORN-012002: Deployment jaxrs-MyJaxrsApplication has no 'KEYCLOAK' authentication method enabled
INFO  : Fri Jun 22 12:34:18 UTC 2018 [io.thorntail.security.keycloak] THORN-012002: Deployment jaxrs-MyJaxrsApplication2 has no 'KEYCLOAK' authentication method enabled

let me check the jwt-auth

**Comment by sberyozkin** [comment]
OK, it all has passed now, I can see in the logs:
INFO  : Fri Jun 22 13:00:19 UTC 2018 [io.thorntail.kernel] THORN-000013: phase [scan] completed in 0.23s
INFO  : Fri Jun 22 13:00:19 UTC 2018 [io.thorntail.jwt-auth] THORN-017001: LoginConfig for deployment jaxrs-MyJaxrsApplication: method - KEYCLOAK, realm - 
INFO  : Fri Jun 22 13:00:19 UTC 2018 [io.thorntail.security.keycloak] THORN-012001: Adding KeycloakConfigResolver to the deployment jaxrs-MyJaxrsApplication
INFO  : Fri Jun 22 13:00:19 UTC 2018 [io.thorntail.security.keycloak] THORN-012002: Deployment jaxrs-MyJaxrsApplication2 has no 'KEYCLOAK' authentication method enabled

I suspect there is a race condition somewhere - I only updated jwt-auth customizer to log as opposed to print to the system err.

**Comment by sberyozkin** [comment]
Actually, I forgot I lowered the priority value in the jwt-auth. Let me put it back and see if it was related

**Comment by sberyozkin** [comment]
Sorry for the noise, but I'm curious what the cause of the CI build failure is given it consistently passes on my laptop

**Comment by sberyozkin** [comment]
OK, it is to do with the customizers with the same event priority being selected in the random order which is expected. 
Ken, this PR should be good to go now :-)

**Comment by sberyozkin** [comment]
@kenfinnigan, can you please approve unless you have some other comments ? Thanks

**Comment by sberyozkin** [comment]
It failed now with the plugin issue (build12) but it was green in builds 9-11 (can be seen in the semaphoreci)

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
