### PR TITLE
SWARM-1906: JAX-RS Fraction does not introspect jar files inside war files when searching for the presence of ApplicationPath

### PR DESCRIPTION
**Pull request by roguexz**
Motivation
----------
I noticed that there were multiple JAX-RS applications deployed for my WAR file. As I debugged further, I realized that the issue was because the JAR file (inside the WAR file) was being viewed as a ByteArrayAsset and was being skipped over. With the recent fixes to IndexView representation, the fix was actually quite simple.

Modifications
-------------
1. During the deployment process, query the IndexView to see if there are **any** classes which contain the @ApplicationPath annotation.
2. If present, do not generate the default JAX-RS Application class.

Result
------
1. Verified a locally patched build and ensured that things are working as desired.
2. Ensured that the build has no errors.

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by heiko-braun** [comment]
add to whitelist

**Comment by kenfinnigan** [comment]
As mentioned on the issue itself, this isn't the fix we want to implement.

What we want to do is defined in SWARM-1471, which is to make the default Application generation optional. With that change this one is not necessary

**Comment by roguexz** [comment]
@kenfinnigan I see that you are recommending the reorganization of the logic for creating the default JAX-RS application class. I can definitely close this PR in favor of the other solution. The concern that I see with SWARM-1471 is that we may end up breaking away from the spec.

If there are no definitions, then the framework should automatically create a default Application instance.

So I am not sure if that would be the right way to achieve it. What do you think?

**Comment by kenfinnigan** [comment]
What we did with WF Swarm by generating that class actually goes against the Java EE spec and caused much confusion.

That's why we need to simplify and only generate the Application class when the developer sets a property to request it

**Comment by roguexz** [comment]
@kenfinnigan Ah! Understood! So basically, WF Swarm provides the ability to declaratively define the JAX-RS application root. That is neat!

I shall close this PR and raise a separate one. This behavior has confused me as well 😄.

**Comment by roguexz** [comment]
@kenfinnigan Quick question ... The fix for 1471 is a breaking change. Do you still want to proceed with it? Or is it used rarely that the impact would be rather low?

**Comment by kenfinnigan** [comment]
To fix it we're going to have to break the behavior at some point

**Comment by roguexz** [comment]
Closing this PR. Will raise one that fixes the issue identified in SWARM-1471.

**Pull request closed without merging**
