### PR TITLE
SWARM-752: Enable Module's MBeanServer

### PR DESCRIPTION
**Pull request by gastaldi**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

---
## Motivation

Debugging Module classloaders can be a pain most of the times. JBoss Modules offers some MBeans to help in this (awful) task.
## Modifications

Called ModuleLoader#installMBeanServer using reflection since the method is not public
## Result

Running jconsole you should see the jboss.modules mbeans in a running swarm app

### CODE REVIEW

**Review by bobmcwhirter — APPROVED** [review]
Just formatting issues, else, good.

**Comment by kenfinnigan** [comment]
Should this be done in Swarm or lower down?

**Comment by bobmcwhirter** [comment]
Ah, good point.  Maybe in our BootModuleLoader's ctor, so it occurs early on?

**Comment by gastaldi** [comment]
That should be executed just once, is the BootModuleLoader's ctor executed once too?

**Comment by gastaldi** [comment]
Preferably before any JBoss Modules class is used

**Comment by bobmcwhirter** [comment]
our BootModuleLoader ctor should occur even earlier than Swarm.

jboss-modules bootstraps by looking for the boot.module.loader property, and instantiating it to get started.  That's the earliest we can jack in, besides bootstrap.Main, which isn't used when non-uberjar.

And yah, only once for that ctor.

**Comment by gastaldi** [comment]
When calling `ModuleLoader.installMBeanServer` in the `BootModuleLoader` ctor, some log.trace() statements are performed, thus initializing JUL prematurely and screwing up the log output. Any suggestions?

**Comment by bobmcwhirter** [comment]
Ah, then definitely _after_ we do the logmanager setup.

**Pull request merged**
