### PR TITLE
Fix #SWARM-705 - Unable to create -swarm.jar

### PR DESCRIPTION
**Pull request by AndyGee**
This resolves the issue as described by https://issues.jboss.org/browse/SWARM-705

### CODE REVIEW

**Comment by gastaldi** [comment]
It seems that nothing has changed except having some code extracted as methods, can you elaborate on how is that supposed to fix the issue?

**Comment by gastaldi** [comment]
Ah @emag pointed out the `synchronized` keyword on the methods, so this seems to be a racing issue? Does it happen only in Windows?

**Comment by gastaldi** [comment]
Ok to test

**Review by gastaldi — APPROVED** [review]

**Comment by AndyGee** [comment]
Hi guys, hold on this. It has improved somewhat, but I'm still getting this issue.

**Comment by AndyGee** [comment]
Still not found what is holding the file lock on delete, however, the overwrite succeeds at:

repackaged.as(ZipExporter.class).exportTo(file, true);

So the strategy is to ensure we have the 'backup', try and delete, and then write/overwrite the target - This does not break the intention.

**Comment by gastaldi** [comment]
Can you use YourKit or a profiler to identify what's holding the file? Maybe we forgot to close a stream?

**Comment by AndyGee** [comment]
Found and reported the culprit: https://issues.jboss.org/browse/SHRINKWRAP-511

I don't know what the release turnaround is for ShrinkWrap, so I would suggest merging this as a workaround until it is resolved - It provides a consistent build for Windows until then.

**Comment by gastaldi** [comment]
I think ShrinkWrap needs to be updated too?

**Comment by kenfinnigan** [comment]
This is a workaround until ShrinkWrap is released

**Pull request merged**
