### PR TITLE
Upgraded to smallrye-open-api 1.0.1 (v2)

### PR DESCRIPTION
**Pull request by EricWittmann**
Signed-off-by: Eric Wittmann <eric.wittmann@gmail.com>

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by kenfinnigan — DISMISSED** [review]

**Comment by kenfinnigan** [comment]
Looks like CI failed on MP Standalone server because of:

java.lang.NoClassDefFoundError: org/jboss/logging/Logger from within SmallRye ArchiveUtil

**Comment by mkouba** [comment]
@EricWittmann You need to add `org.jboss.logging` as a module dependency to https://github.com/thorntail/thorntail/blob/master/fractions/microprofile/microprofile-openapi/src/main/resources/modules/io/smallrye/smallrye-open-api/main/module.xml.

**Comment by EricWittmann** [comment]
OK will do.

**Comment by kenfinnigan** [comment]
Looks like the MP OpenAPI TCK now fails

**Review by mkouba — APPROVED** [review]

**Pull request merged**
