### PR TITLE
Use `bom` in HOWTOs instead of `bom-all`

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Provides the capability for them to work indentically in
both upstream and downstream, all with normal `bom`.

- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by Ladicek** [comment]
Just wondering why you delete the `integraion-test` goal from Failsafe?

**Comment by bobmcwhirter** [comment]
Because verify implies it I think?

**Comment by Ladicek** [comment]
Well `mvn verify` indeed implies going through `integration-test` phase, but adding `verify` goal AFAIK doesn't imply adding the `integration-test` goal. The docs http://maven.apache.org/surefire/maven-failsafe-plugin/usage.html seem to confirm, but I'd have to check to be sure.

**Comment by bobmcwhirter** [comment]
Ah. Hrm. I’ll add it back.

**Pull request merged**
