### PR TITLE
THORN-2090: Override AnnotationDeploymentScenarioGenerator.

### PR DESCRIPTION
**Pull request by mkouba**
- there was an incompatible change in Arquillian SPI in 1.3.0, see also
ARQ-2173

### CODE REVIEW

**Review by Ladicek — DISMISSED** [review]

**Comment by Ladicek** [comment]
Looks like rebasing would be nice, but the change itself LGTM.

**Comment by Ladicek** [comment]
Just thinking, will this affect older Arquillian versions? I guess hopefully maybe probably not, but I don't really know.

**Comment by mkouba** [comment]
@Ladicek which versions do you have in mind? TT2 is currently using 1.1.x and I've tested this manually with 1.3.0 and 1.4.1.

**Comment by Ladicek** [comment]
I mean if it's good with today's 1.1.x.

**Comment by mkouba** [comment]
@Ladicek CI builds passed so I suppose it is ;-)

**Comment by Ladicek** [comment]
Ha, yea, this is about `@DefaultDeployment`, which we use a lot in the tests. Thanks!

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
