### PR TITLE
[SWARM-1970] Using a swarm classifier

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by kenfinnigan — DISMISSED** [review]

**Comment by sberyozkin** [comment]
Thanks Ken... I might need to duplicate that code as it looks like the same function is used to load 'war' artifacts as well :-)

**Review by kenfinnigan — APPROVED** [review]

**Comment by Ladicek** [comment]
This looks related to https://issues.jboss.org/browse/SWARM-1238 ?

**Comment by roguexz** [comment]
Would this fix also solve the issue reported in [SWARM-1965](https://issues.jboss.org/browse/SWARM-1965)? Or is that a different problem?

**Comment by sberyozkin** [comment]
Ladislav, yes, SWARM-1970 is a duplicate, sorry I did not spot that earlier :-)

**Comment by Ladicek** [comment]
Not a problem, thanks!

**Pull request merged**
