### PR TITLE
Upgraded to microprofile-openapi 1.1.1 (along with the SmallRye impl)

### PR DESCRIPTION
**Pull request by EricWittmann**
Signed-off-by: Eric Wittmann <eric.wittmann@gmail.com>

This PR addresses the following issue:  https://issues.jboss.org/browse/THORN-2260

- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by EricWittmann** [comment]
I have been able to build locally, but only with `-DskipTests`.  When I try to run the MicroProfile OpenAPI TCK, I get a number of stack traces related to Arquillian failing to delete temp files (during undeployment).  The first few TCK tests pass, but fairly quickly I start getting the following error:

```
org.jboss.msc.service.StartException in service org.wildfly.undertow.listener.default: Address already in use: bind /127.0.0.1:8080
```

I have never been able to successfully run the TCK tests locally, so I'm hoping that the CI build is OK.  If not, I'll have to address any issues found in CI as separate commits.

**Comment by EricWittmann** [comment]
The build on **semaphoreci** is failing, but it doesn't seem related to my changes?  It's hard for me to tell:

```
[ERROR] Plugin io.thorntail:thorntail-maven-plugin:2.3.1.Final-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact io.thorntail:thorntail-maven-plugin:jar:2.3.1.Final-SNAPSHOT -> [Help 1]
```

**Comment by Ladicek** [comment]
You can ignore SemaphoreCI, that's only for the `v4` branch.

**Comment by Ladicek** [comment]
I don't know why, but there's one test in the MP OpenAPI TCK which didn't shutdown the running Thorntail instance, and all the subsequent ones failed with "Address already in use".

**Comment by michalszynkiewicz** [comment]
I tried running the microprofile-tck/openapi locally for this PR and got some failures: https://gist.github.com/michalszynkiewicz/835043b5d4d5e3c17d1bce285dd2b7d1

**Comment by EricWittmann** [comment]
The full output log for this can be found here: 

https://gist.github.com/EricWittmann/1766ff930d0fba3ad0ab82dd7d3f24c6

You can see that around line 500 or so is where the first `Address already in use` problem shows up.

I honestly don't know how to debug this.  Anyone have any ideas?

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
Hi, will have a quick look at this PR as well, thanks

**Comment by EricWittmann** [comment]
Thanks for looking at this!  I don't know why the thorntail instance doesn't get properly shut down in one of the tests.

**Comment by sberyozkin** [comment]
Hi @EricWittmann, np at all.
[OASConfigWebInfTest](https://github.com/eclipse/microprofile-open-api/blob/mp-openapi-1.1.1/tck/src/main/java/org/eclipse/microprofile/openapi/tck/OASConfigWebInfTest.java) causes the problems. It is the only test which extends another test class [OASConfigScanClassTest](https://github.com/eclipse/microprofile-open-api/blob/mp-openapi-1.1.1/tck/src/main/java/org/eclipse/microprofile/openapi/tck/OASConfigScanClassTest.java) with its own Deployment.   

If I change [OASConfigWebInfTest](https://github.com/eclipse/microprofile-open-api/blob/mp-openapi-1.1.1/tck/src/main/java/org/eclipse/microprofile/openapi/tck/OASConfigWebInfTest.java) to extend from AppTestBase and copy a test from OASConfigScanClassTest then OASConfigWebInfTest causes no problems.

Can you please confirm as well ?

It looks like Thorntail can not handle a test suite which has 2 Deployments. @Ladicek, @mkouba, is it correct ?

If yes then the fix is to update OASConfigWebInfTest in the MP OpenApi and may be as well have  OASConfigWebInfTest copied to the Thorntail microprofile test suite to ThorntailOASConfigWebInfTest and updated as suggested above, with OASConfigWebInfTest itself being excluded.

**Comment by Ladicek** [comment]
I don't recall seeing any test that would have two `@Deployment`s. Isn't Arquillian supposed to ignore the `@Deployment` from ancestor class, if the `@Deployment` in subclass is on a method with the same name? IDK, but I think I've read something like that somewhere...

**Comment by sberyozkin** [comment]
The 2nd Deployment has an [order](https://github.com/arquillian/arquillian-core/blob/master/container/test-api/src/main/java/org/jboss/arquillian/container/test/api/Deployment.java#L77) property, may be this is why the one in the super class is not ignored

**Comment by Ladicek** [comment]
I don't really know. But I can imagine two deployments confuse our Arquillian adapter a lot.

**Comment by EricWittmann** [comment]
I am going to try to get this fixed on the Microprofile-OpenAPI side by updating the TCK.  Hopefully I can get that fixed there within the week.  So please hold off on any other changes until we see if I can get that done. :)

**Comment by EricWittmann** [comment]
For tracking/reference purposes:  https://github.com/eclipse/microprofile-open-api/pull/335

**Comment by EricWittmann** [comment]
Update: I have fixed the upstream TCK tests to no longer have multiple deployments.  And I've rebuilt that (and smallrye) locally and then run the thorntail MP+OpenAPI TCK suite.  All greeeeeeen!  



I'm submitting a SmallRye PR to update versions there.  Then we can do a SmallRye OpenAPI release and then update this PR and everything should work.  

Thanks @sberyozkin for figuring out what was wrong!

**Comment by sberyozkin** [comment]
Hi @EricWittmann, that is a super fast fix, np at all, thanks

**Comment by sberyozkin** [comment]
retest this please

**Review by sberyozkin — APPROVED** [review]
Windows build is failing due to the pulling some artifact issue

**Comment by Ladicek** [comment]
This scared me a little, but no, it's actually the usual disk space issue :-) But that scares me anyway, because I did a disk space cleanup of all Windows build agents just last week...

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
So this can be merged, right?

**Comment by sberyozkin** [comment]
Yes, merging now

**Pull request merged**
