### PR TITLE
opentracing needs to be in product profile

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
What's the requirement for cli, hibernate-search and infinispan to be included?

**Comment by heiko-braun** [comment]
@kenfinnigan  It's derived from your fraction landscape spreadsheet. The are marked as supported.

**Comment by kenfinnigan** [comment]
Ah.

I don't know how much John has reviewed that landscape in the past.

If we don't think those three are necessary, we don't have to productize them this release

**Comment by Ladicek** [comment]
I think OpenTracing is a product requirement, no? I remember we debated including the Jaeger fraction too (I still think it's probably a good idea).

From the rest, I don't remember any discussion or requirement -- except maybe Infinispan, which might be required for the Caching mission?

**Comment by heiko-braun** [comment]
@Ladicek yes, we keep OT and remove the others for now

**Comment by kenfinnigan** [comment]
Ooh, hadn't thought of that.

@michalszynkiewicz, does Cache mission use Infinispan fraction?

**Comment by kenfinnigan** [comment]
Per IRC discussion, Cache mission uses Hot Rod client not Infinispan fraction

**Comment by Ladicek** [comment]
Ah OK, thanks!

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
