### PR TITLE
SWARM-xxx: SWARM-1039, LoggingFraction moduleHandler additions

### PR DESCRIPTION
**Pull request by starksm64**
Motivation
----------
Helpers to configure the org.jboss.modules.Module ModuleLogger implementation

Modifications
-------------
Added 4 modules* helper methods

Result
------
This allows one to enable logging output from the JBossModules layer using a simple setup like the following:

        // Create a trace level logging setup with a JBossModules JUL bridge
        swarm.fraction(LoggingFraction.createTraceLoggingFraction()
                .modulesJDKLogger()
        );

- [*] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [*] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [*] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [*] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Ok to test

**Comment by bobmcwhirter** [comment]
Add to whitelist

**Review by gastaldi — COMMENTED** [review]
Does it make sense to have theseethods in LoggingFraction or should it be placed somewhere else? This looks specific to JBoss Modules

**Comment by starksm64** [comment]
These are not thresholds, they are ways to bridge the modules layer logging to the rest of the swarm app. The only way to do this is via the modules specific API. Without this change, the LoggingFraction has no way to configure logging at the JBossModules layer.

**Comment by gastaldi** [comment]
Sorry, not thresholds, methods. Typo

Em 27 de jan de 2017 21:21, "Scott M Stark" <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment]
My point is that you can call Module.setModuleLogger anywhere without having LoggingFraction installed, that's why I don't think it should belong to this fraction.

**Comment by kenfinnigan** [comment]
@gastaldi if not in LoggingFraction, where?

User space code doesn't have automatic access to `Module`

**Comment by gastaldi** [comment]
I am not sure if the Modules logging implementation should be allowed to be changed by the user. At the very least we should provide one that is compatible with the logging mechanism used by Swarm. Then we could have some helper methods in LoggingFraction that would tune that as needed. 

But that´s just my opinion, open for ideas.

**Comment by gastaldi** [comment]
Anyway feel free to ignore me if that doesn´t make sense :)

**Comment by starksm64** [comment]
The default logging implementation bridge is the NoopModuleLogger, which as you would expect does nothing. It would probably be good that if one invoked the LoggingFraction.applyDefaults(Level) is call with a Level of DEBUG or lower, that modulesJDKLogger() was called as the most common usecase for enabling the JBossModules logging is debugging. 

Alternatively this could go into the org.wildfly.swarm.Swarm class itself since that is where logging is setup, and there is already some integration with Module.setModuleLogger when debugBootstrap has been specified.

**Comment by gastaldi** [comment]
Agreed.

Given that this is low-level logging I guess it makes sense to be in the Swarm class, but I'll leave that for @kenfinnigan and @bobmcwhirter to decide.

**Comment by kenfinnigan** [comment]
It might make sense to move to Swarm(), as that's where a lot of module setup happens.

Doing this in the LoggingFraction *may* be too late.

However, there is https://github.com/wildfly-swarm/wildfly-swarm/blob/master/core/container/src/main/java/org/wildfly/swarm/Swarm.java#L176 in debug mode. Which we know has issues if that's set to JUL.

**Comment by starksm64** [comment]
Ok, I'll do another pull request against the Swarm.java class. 

I'll look at having an initial debug mode using the StreamModuleLogger to stderr during the initial bootstrap, and switch to whatever the user specified after the swarm logging is initialized.

**Comment by gastaldi** [comment]
Closing as @starksm64 mentioned he'd do another PR.

**Comment by heiko-braun** [comment]
Closing due to inactivity

**Pull request closed without merging**
