### PR TITLE
SWARM-1065 - Better logging granularity.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Motivation
----------

We need better control of what gets logged at which levels, and
be able to increase/decrease the output based on use-case.

Modifications
-------------

Split some SwarmMessages into Config and Metrics-related
messages.

Result
------

Somewhat less output by default.

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]
Do we need to renumber SwarmMessages to remove gaps?

**Comment by bobmcwhirter** [comment]
I think that is a discussion we need to have.  This purely moved them to different categories, while retaining the original numbering.  So WFSWARM-00034 is still WFSWARM-0034, but moved from `org.wildfly.swarm` to `org.wildfly.swarm.config`.

I think numbering needs to be unique for the entire prefix (WFSWARM) irrespective of the category used.

I'm okay with "breaking" the current numbering to clean stuff up and institute a better numbering scheme (groups of 100 or 1000 or such by class)

**Comment by kenfinnigan** [comment]
Good point, forgot about the prefixing thing.

Right, so maybe a group of 1000 per class?

**Comment by bobmcwhirter** [comment]
retest this please

**Pull request merged**
