### PR TITLE
SWARM-595 -- General cleanup of org.wildfly.swarm.runtime.**

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Attempt to organize classes into logical packages.

Also remove a class or two that is no longer actually used.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
test this please

**Comment by bobmcwhirter** [comment]
That seemed to break. WTF?

## 

Sent from my iPhone

On Aug 11, 2016, at 10:04 PM, Ken Finnigan notifications@github.com wrote:

Merged #69 https://github.com/wildfly-swarm/wildfly-swarm/pull/69.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/wildfly-swarm/wildfly-swarm/pull/69#event-753498419,
or mute the thread

**Comment by bobmcwhirter** [comment]
Http 413 on upload. Entity too large. Will figure it out.

**Comment by kenfinnigan** [comment]
Had a brief look last night and couldn't figure out why it was having issues

**Pull request merged**
