### PR TITLE
THORN-2166 Fix topology-openshift in OpenShift 3.10

### PR DESCRIPTION
**Pull request by juangon**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

Tested in 3.9 too.

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I take it you ran the entire https://github.com/rhoar-qe/thorntail-openshift-test-suite to verify?

**Comment by juangon** [comment]
I did just the topology one as it is the only place where this library is used (topology openshift). I can try with all tests if you want of course

**Comment by Ladicek** [comment]
Ah sure, right :-) No, that's fine.

**Comment by Ladicek** [comment]
Windows test failures are unrelated (MP Config and MP FT TCKs, management console).

**Pull request merged**
