### PR TITLE
SWARM-1373: Print warning when mainClass property set

### PR DESCRIPTION
**Pull request by heiko-braun**
Motivation
----------
We are moving away from custom main()

Modifications
-------------
Print warning when property is still used during builds.

Result
------
No impact on functionality

### CODE REVIEW

**Review by Ladicek — CHANGES_REQUESTED** [review]
`WildFly Swarm reference` instead of `WildflySwarm reference`, and it should probably print the URL: https://reference.wildfly-swarm.io/

**Comment by heiko-braun** [comment]
@Ladicek The URL doesn't work in product builds.

**Comment by Ladicek** [comment]
Hmm, not sure if we will have a different URL for product, but it's OK.

**Review by Ladicek — DISMISSED** [review]

**Comment by Ladicek** [comment]
Actually the typo is still there in the Gradle plugin, but that doesn't concern me _that_ much :-)

**Review by Ladicek — DISMISSED** [review]

**Comment by kenfinnigan** [comment]
As @Ladicek mentioned, this needs a link to the YAML reference guide, as described in the JIRA.

At this stage we don't know if there will be a product specific version of the reference guide. If there does end up being one, we can sort that out later.

Not sure it's necessary to put the calls into each Mojo, why not add the `deprecationWarnings` logic into constructor of `AbstractSwarmMojo`?

**Comment by kenfinnigan** [comment]
Forgot to add, looks like the Maven Plugin testsuite needs to be modified to support the WARNING log now

**Comment by Ladicek** [comment]
I'm fine with the WARNING log test being commented out for now -- I'd then think about what to do with the test. Maybe we don't have to test using `main` if we're deprecating it.

**Comment by heiko-braun** [comment]
@kenfinnigan seems the field values are injected after the ctor, hence the separation.

**Comment by kenfinnigan** [comment]
Thanks for checking

**Comment by heiko-braun** [comment]
@Ladicek Do you suggest to remove the WITH_MAIN tests? Or simply remove the assertion on WARNING log messages?

**Comment by Ladicek** [comment]
@heiko-braun I'd suggest commenting out the assertion on WARNING log messages for now. And I will file a JIRA for myself to get back to it -- maybe removing custom main tests would be best, but I'd rather think about it more.

**Comment by heiko-braun** [comment]
Incorporated all changes and squashed into one

**Pull request merged**
