### PR TITLE
fix running integration tests in the testsuite module

### PR DESCRIPTION
**Pull request by Ladicek**
- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by sberyozkin** [comment]
I tested your branch and indeed Vertx tests run now by default but can be properly skipped as well.
Vert.x test itself is failing for me at least but may be it is a separate issue

**Comment by Ladicek** [comment]
Correct, the Vert.x test is failing.

**Comment by sberyozkin** [comment]
What is interesting is the semaphoreci build passed though :-)

**Review by sberyozkin — APPROVED** [review]
Changes are correct, the Vert.x test issue is a separate one

**Pull request merged**
