### PR TITLE
SWARM-1175 topology-webapp missing a dependency on WF naming service

### PR DESCRIPTION
**Pull request by ppalaga**
- [✓] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [✓] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [✓] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [✓] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Okay to test

**Comment by kenfinnigan** [comment]
Should this be the naming module or fraction it depends on?

**Comment by ppalaga** [comment]
> Should this be the naming module or fraction it depends on?

I primarily mean the runtime naming service. https://github.com/wildfly-swarm/wildfly-swarm/pull/415/commits/86ab8747aa7ebd7cf92a241f5969bb2616acbe7d#diff-0dec12ca91379a5ad5db58ed5f7ac575R54

`org.wildfly.swarm:naming` maven dep was already there before this change, although only indirectly via `topology`.

I added the naming module dep https://github.com/wildfly-swarm/wildfly-swarm/pull/415/commits/86ab8747aa7ebd7cf92a241f5969bb2616acbe7d#diff-d17b7d0d951efb25032dc3188947efa5R10 so that the `DefaultNamespaceContextSelectorService` can be  loaded properly. Without it, I was getting `ClassNotFoundExceptions`.

**Comment by kenfinnigan** [comment]
Ok, though we should probably add `naming` as a dependent fraction in `pom.xml` as well to ensure that the subsystem is present as well.

I think that's the case anyway, @bobmcwhirter ?

**Comment by ppalaga** [comment]
8c68010 replaces the previous iteration. 

I have added the naming fraction https://github.com/wildfly-swarm/wildfly-swarm/pull/415/commits/8c68010a01db32d581721849c1e651c715fd5f6c#diff-c5f2de67563faa88fae7b7221abb8bcfR42

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
