### PR TITLE
[SWARM-2018] Fix documentation on maven plugin

### PR DESCRIPTION
**Pull request by kg6zvp**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
Or you can have `<configuration>` directly under `<plugin>`, but both work fine.

**Review by Ladicek — APPROVED** [review]

**Comment by kg6zvp** [comment]
That does seem like a better way to show in the example, but I left it inside `<executions/>` since that was where it was originally. Should it be moved?

**Comment by Ladicek** [comment]
No, this is fine IMO.

I wonder why CI didn't kick in...?

test this please

**Comment by kg6zvp** [comment]
I'm guessing CI didn't kick in because the changes were isolated to documentation (not sure what rules CI on this project is using).

My understanding based on the contribution guide was that testing was not required for documentation-only changes. In any case, I'll start the tests running now.

**Comment by kg6zvp** [comment]
Update: All tests pass locally on the latest version of this branch.

**Comment by Ladicek** [comment]
Thanks @kg6zvp, I think it's actually because the CI server is down :-) Though I agree this change doesn't strictly need it.

**Comment by Ladicek** [comment]
test this please

**Comment by Ladicek** [comment]
ok to test

**Pull request merged**
