### PR TITLE
Align asm versions

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
test this please

**Comment by heiko-braun** [comment]
The underlying error seems to be:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project undertow: Compilation failure: Compilation failure:
[ERROR] /C:/opt/jenkins/workspace/wildfly-swarm-pull-request-windows/fractions/javaee/undertow/src/main/java/org/wildfly/swarm/undertow/descriptors/FaviconFactory.java:[22,33] cannot find symbol
[ERROR] symbol:   class ClassRemapper
[ERROR] location: package org.objectweb.asm.commons
[ERROR] /C:/opt/jenkins/workspace/wildfly-swarm-pull-request-windows/fractions/javaee/undertow/src/main/java/org/wildfly/swarm/undertow/descriptors/FaviconFactory.java:[51,9] cannot find symbol
[ERROR] symbol:   class ClassRemapper
[ERROR] location: class org.wildfly.swarm.undertow.descriptors.FaviconFactory
[ERROR] /C:/opt/jenkins/workspace/wildfly-swarm-pull-request-windows/fractions/javaee/undertow/src/main/java/org/wildfly/swarm/undertow/descriptors/FaviconFactory.java:[51,37] cannot find symbol
[ERROR] symbol:   class ClassRemapper
[ERROR] location: class org.wildfly.swarm.undertow.descriptors.FaviconFactory
[ERROR] /C:/opt/jenkins/workspace/wildfly-swarm-pull-request-windows/fractions/javaee/undertow/src/main/java/org/wildfly/swarm/undertow/descriptors/FaviconFactory.java:[75,9] cannot find symbol
[ERROR] symbol:   class ClassRemapper
[ERROR] location: class org.wildfly.swarm.undertow.descriptors.FaviconFactory
[ERROR] /C:/opt/jenkins/workspace/wildfly-swarm-pull-request-windows/fractions/javaee/undertow/src/main/java/org/wildfly/swarm/undertow/descriptors/FaviconFactory.java:[75,37] cannot find symbol
[ERROR] symbol:   class ClassRemapper
[ERROR] location: class org.wildfly.swarm.undertow.descriptors.FaviconFactory
[ERROR] -> [Help 1]
[ERROR] 
```

**Comment by kenfinnigan** [comment]
I don’t think this change will work. As part of updating to WF 11 there was an update to ASM that included API changes

**Comment by heiko-braun** [comment]
retest this please

**Comment by heiko-braun** [comment]
@kenfinnigan hm, I don't see a productised 6.0 version. Shouldn't it be there if WF 11 depends on ASM 6.0?

**Comment by heiko-braun** [comment]
closing to further verify

**Pull request closed without merging**
