### PR TITLE
SWARM:1824: upgrading the Teiid version to 10.0.3

### PR DESCRIPTION
**Pull request by rareddy**
- [x ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by heiko-braun** [comment]
add to whitelist

**Comment by heiko-braun** [comment]
test this please

**Review by heiko-braun — DISMISSED** [review]

**Comment by kenfinnigan** [comment]
Once CI is back up we can do a release of config-api for teiid and then this PR can be updated with that new version

**Comment by heiko-braun** [comment]
Kicked of a build, hang tight:
https://ci.wildfly-swarm.io/job/teiid-config-api-release/4/

**Comment by heiko-braun** [comment]
@rareddy 1.1.1.Final is available. Can you update the PR to include it? 
http://central.maven.org/maven2/org/wildfly/swarm/teiid-config-api/1.1.1.Final/

**Comment by rareddy** [comment]
sure

**Comment by rareddy** [comment]
@heiko-braun done

**Comment by heiko-braun** [comment]
thanks @rareddy

**Pull request merged**
