### PR TITLE
WFNOSQL-22 update wildfly-nosql to base on WildFly 11.0.0.Final

### PR DESCRIPTION
**Pull request by scottmarlow**
- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by bobmcwhirter — APPROVED** [review]
Well that was easy. No config-api regen required?

**Comment by scottmarlow** [comment]
Good idea, I'll regen config-api also

**Comment by bobmcwhirter** [comment]
At least that’ll keep the core config-api versions aligned.

**Comment by scottmarlow** [comment]
nosql-config-api is now in sync + regenerated and referenced by this pr :)

**Comment by juangon** [comment]
Why failed tests in Windows if final status was "SUCCESS"?

**Comment by scottmarlow** [comment]
Hmm, info from failed org.eclipse.microprofile.metrics.tck.MeterTest.testRates on windows:
java.lang.AssertionError: expected:<0.184> but was:<0.2>
	at org.eclipse.microprofile.metrics.tck.MeterTest.testRates(MeterTest.java:113)

Could that be an issue in how the test was written?

**Comment by scottmarlow** [comment]
Yeah, looks like a test issue as I see nearly the same in https://ci.wildfly-swarm.io/job/wildfly-swarm-pull-request-windows/743/

**Comment by bobmcwhirter** [comment]
Dang floating-point math.

**Comment by bobmcwhirter** [comment]
Adding +hold to this, and will cherry-pick it over to the big WF11 PR.

**Comment by scottmarlow** [comment]
Closing, as was included in the big WF11 PR. :)

**Pull request closed without merging**
