### PR TITLE
Replaced @Singleton with @ApplicationScoped

### PR DESCRIPTION
**Pull request by gastaldi**
Based on https://gist.github.com/bobmcwhirter/6c271c6fbbb783df606ea4fa572df652, @Singleton should be replaced with @ApplicationScoped

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Test this please

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
Ok to test

**Comment by gastaldi** [comment]
Please retest

**Comment by bobmcwhirter** [comment]
Yah, turns out we do _not_ want to do this.

Since some of these interfaces are in spi:api (not :runtime), we don't want to Proxy them (because @ApplicationScoped proxies) because then we have to mix weld3 into the spi:api.

We may want/need to move them to :runtime, but that could also affect plans for user-space usage of these interfaces in the future.

**Pull request closed without merging**
