### PR TITLE
SWARM-1794: MP FT - remove CommandInterceptorTest.testTimeoutFallback().

### PR DESCRIPTION
**Pull request by mkouba**
- this test was replaced with
org.wildfly.swarm.microprofile.faulttolerance.deployment.timeout.TimeoutTest

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]

**Comment by kenfinnigan** [comment]
Passed on Linux but on Windows an FT TCK test failed.

Is it a problem or just an anomaly?

**Comment by mkouba** [comment]
That's a known issue - `BulkheadAsynchRetryTest` fails intermittently, esp. on windows. Antoine was looking into this but so far we don't have a clue what's wrong. I'll create a jira issue and take it over.

**Comment by antoinesd** [comment]
Unable to reproduce the error in my dev env (macos + JDK 1.8.0_152) after more than 30 attempts. I'll probably have to install a windows VM and study this issue in it.

**Comment by mkouba** [comment]
@antoinesd I'd guess it's a similar problem as with `BulkheadSynchRetryTest`. Let me check this particular test as well.

**Comment by mkouba** [comment]
Ok so looking at the test output and source it seems that `TestData.check()` is invoked before most of the async `BulkheadRapidRetry55MethodAsynchBean.test()` wrappers are executed. This could happen for many reasons (e.g. the thread pool init may take some time). I think the test should be fixed (and excluded for now). I'm going to create a separate FT issue.

**Pull request merged**
