### PR TITLE
Added deprecation notice to the Monitor fraction (SWARM-1696)

### PR DESCRIPTION
**Pull request by tradej**
Documents SWARM-1696

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by Ladicek — DISMISSED** [review]

**Review by heiko-braun — DISMISSED** [review]
lgtm, thanks @tradej

**Comment by mkouba** [comment]
Shouldn't we also change the `swarm.fraction.stability` of Monitor fraction to `DEPRECATED`?

**Comment by Ladicek** [comment]
+1 to changing the stability index.

**Comment by heiko-braun** [comment]
@tradej can you update the pr to change the swarm.fraction.stability index?

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
