### PR TITLE
update to keycloak 2.1.0.Final

### PR DESCRIPTION
**Pull request by sebastienblanc**

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Have you manually verified that the standalone keycloak-swarm.jar continues to work?

**Comment by sebastienblanc** [comment]
@bobmcwhirter yep, I have both tested that keycloak-server works and keycloak fraction with my test apps. But I will double check with Keycloak team if `module.conf` needs to be updated

**Comment by sebastienblanc** [comment]
@stianst is there any updates in the modules between kc 1.9.x and 2.x ? If I quickly compare I can see the `keycloak-authz-x`  modules but these are added transitively with `keycoak-services`

**Comment by stianst** [comment]
There was some new modules introduced by authz other than that I can't think of any

**Comment by bobmcwhirter** [comment]
We do use their feature-pack, so hopefully they are all just available to us.  I think this is good to go.

**Pull request merged**
