### PR TITLE
THORN-1647: Plugin topology-consul is getting error and it does not allow the health checks

### PR DESCRIPTION
**Pull request by McIntozh**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

I've upgraded `consul-client` to the latest version. Now newer versions of consul are supported and the "Method not allowed" error is not thrown.

The new client moved from `resteasy` to `okhttp3`, so I had to add this (aswell as `okio` and `retrofit2`) to `modules.xml`. Also I had to update `okhttp3` to a newer version.

Build-parent POM mentions `okhttp3` and` okhttp3-ws` are not used, this deos not seem to be true, `topology-openshift` seems to use that.
**Unfortunately** `okhttp3-ws` is deprecated and no newer version is available, so I fixed it to `3.4.2`.
Bulding worked fine, but I cannot test if the openshift-fraction still works as expected.

Perhaps someone could look over my changes to confirm I did not break anything by changing dependency versions.

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hi, thanks for the patch. Can you please look at 
https://github.com/thorntail/thorntail-examples/tree/master/ribbon-consul
and see if something needs to be adjusted there as well ?
Note an old PR for that demo is still open,
https://github.com/thorntail/thorntail-examples/pull/155,
but I suspect it needs to be closed and a new one created

Thanks

**Comment by McIntozh** [comment]
Hi @sberyozkin,
I think PR 155 is obsolete.
Following the description of the `ribbon` example and adding `-Dswarm.bind.address=127.0.0.1` I could run the projects  without problems. I could update the `README.md` with this information.

But `mvn verify -Pconsul` fails for me with `FileNotFoundException: null/example-ribbon-consul-frontend.war` this should not be related to my changes and I don't know how to solve this.

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
Hi, that PR has been updated and I just merged 
https://github.com/thorntail/thorntail-examples/pull/186

I guess we'll need to get at least Linux build passing here first

**Review by Lasrik — APPROVED** [review]

**Comment by Lasrik** [comment]
Can somone please repeat the build. The sempaphore build fail is in my eyes an error in the build scripts. I successfully builded the source.

**Comment by kenfinnigan** [comment]
ok to test

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
