### PR TITLE
SWARM-943: Upgrade to wildfly-camel-4.4.0

### PR DESCRIPTION
**Pull request by jamesnetherton**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------
Upgrade camel fractions to use wildfly-camel 4.4.0

Modifications
-------------
Bumped camel fraction pom versions for wildfly-camel and camel

Result
------
Camel fractions integrate with the latest wildfly-camel version 4.4.0

### CODE REVIEW

**Comment by kenfinnigan** [comment]
ok to test

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
@jamesnetherton could 2.18.1 be broken in central? Looks like CI is unable to open the jar for it?

**Comment by jamesnetherton** [comment]
@kenfinnigan That's weird! I'll try and build again from scratch locally with a fresh m2 repo and see what happens.

**Comment by kenfinnigan** [comment]
@jamesnetherton seems like it might be ok now

**Comment by gastaldi** [comment]
retest it please

**Comment by gastaldi** [comment]
retest this please

**Comment by gastaldi** [comment]
Retest this please

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
