### PR TITLE
SWARM-823 - Bring-your-own JDBC driver

### PR DESCRIPTION
**Pull request by bobmcwhirter**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------

With our fractions bringing in (via transitivity) particularly
versions of JDBC drivers, and wrapping them in a module.xml,
it's quite difficult to keep up to date, and allow users to
bring alternate versions of these drivers.

Modifications
-------------

Teach WildFly Swarm to not transitively bring in any drivers,
but able to recognize them.  Upon recognition, it can create
a synthetic module.xml and register the driver, regardless
of the actual version of the driver jar is involved.

Result
------

Anything that previously assumed h2 was present will need to
explicitly add a dependency on the h2 JDBC driver jar (with
scope=compile).  Any version is fine.  Likewise for MySQL
or Postgres.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Please hold until I have the paired PR for -examples ready to roll.  But happy to have CI give this a whirl until then.

**Comment by bobmcwhirter** [comment]
Retest this please

**Comment by bobmcwhirter** [comment]
Please continue to hold until -examples PR is landed and reviewed. 

The two PRs _must_ be merged in marginal lock-step.

**Review by kenfinnigan — APPROVED** [review]
Other than adding license headers to new files I think it looks good!

**Comment by bobmcwhirter** [comment]
Thanks. Still going to try deprecating our database fractions but suspect it won't work due to our WEB-INF scraping to remove swarm stuff. Will try nonetheless. Either way I'll self-merge tomorrow sometime.

**Comment by kenfinnigan** [comment]
ah yes, scraping would be an issue indeed

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
Retest this please

**Comment by bobmcwhirter** [comment]
Retest this please

**Comment by bobmcwhirter** [comment]
Continuous testing required because of a Nexus issue which has supposedly been solved by CloudBees now. We shall see.

**Pull request merged**
