### PR TITLE
[SWARM-1942] Adding the install and deploy phase skip instructions to microprofile-tcks/pom.xml

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by michalszynkiewicz — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
Windows failure: org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchRetryTest.testBulkheadRetryClassAsynchronous55

**Comment by sberyozkin** [comment]
Hi Michal, the test passed on Linux so I'd say this PR change is safe if you and Ken agree...I'm off tomorrow. I'll get it retested just to try a Windows test passing...

**Comment by sberyozkin** [comment]
retest this please

**Comment by michalszynkiewicz** [comment]
@sberyozkin I think the error (as well as org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchTest.testBulkheadClassAsynchronous3 in the next attempt) are known issues with MP FT TCK

**Pull request merged**
