### PR TITLE
THORN-2193: Upgrade smallrye-fault-tolerance to 1.0.4

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by antoinesd — DISMISSED** [review]
Now I understand the use of CommandListeners ;-)

**Comment by mkouba** [comment]
retest this please

**Comment by mkouba** [comment]
It seems that `org.wildfly.swarm.microprofile.restclient.ft.FaultToleranceTest` fails. I need to investigate why...

**Comment by mkouba** [comment]
We will need to release 1.0.4 first. See also https://github.com/smallrye/smallrye-fault-tolerance/issues/25. It's not a critical issue but prevents MP Rest Client interception from working correctly in some cases.

**Comment by mkouba** [comment]
retest this please

**Comment by mkouba** [comment]
retest this please

**Review by sberyozkin — APPROVED** [review]

**Comment by mkouba** [comment]
The CI build actually passed: https://ci.wildfly-swarm.io/view/Pull%20Requests/job/thorntail-pull-request-linux/716/

**Pull request merged**
