### PR TITLE
SWARM-1418 - De-manage MSC dependency.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Motivation
----------
By explicitly managing our dependency and module.xml for MSC,
we introduce an opportunity for version skew when going to
product.

Modifications
-------------
Remove and adjust our modules and versions related to JBoss MSC.

Result
------
Fewer things to skew about.

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Though I'm not sure about removing the `module.xml` for `javax.sql.api` -- is that totally unnecessary?

**Comment by bobmcwhirter** [comment]
Well, I figured while I was in there, I could see how much we could delete, particularly if it's just replicated from the WildFly/EAP feature-pack and module.xml's.

Seems like javax.sql.api and javax.api all could go away from our bootstrap module.  Might as well, to prevent possible future skew, even if not a problem immediately.

So, I removed those module.xml's and excluded them from the module-finders that were referencing them, I believe.

**Comment by bobmcwhirter** [comment]
Yah, core builds, and -examples pass with both uberjar and non-uberjar with this PR.

So I think it's safe/good/right to remove all that we can.

**Comment by Ladicek** [comment]
Ah, right, obviously we get the `module.xml` for `javax.sql.api` from WildFly. It's just that it isn't related to MSC what triggered my question.

**Comment by bobmcwhirter** [comment]
Yeah, my commit message is sub-par. :)

**Pull request merged**
