### PR TITLE
test wildfly-swarm-pull-request-linux change with minor upgrade wildfly.nosql.feature-pack to 1.0.0.Alpha4

### PR DESCRIPTION
**Pull request by scottmarlow**
- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by scottmarlow** [comment]
Please keep this pr open for a bit, using it to hack on wildfly-swarm-docker-test-linux from wildfly-swarm-pull-request-linux

**Comment by scottmarlow** [comment]
testing is complete, just verified that wildfly-swarm-docker-test-linux failures are propagated to wildfly-swarm-pull-request-linux.  Will test once more so this change can be merged.

**Comment by kenfinnigan** [comment]
@scottmarlow, what's the status of this? Can merge or close?

**Comment by scottmarlow** [comment]
@kenfinnigan yes, it can be merged now, thanks!

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
