### PR TITLE
SWARM-1536: topology-openshift uses wrong namespace when pod runs in a different namespace than the image was built in

### PR DESCRIPTION
**Pull request by Ladicek**
Motivation
----------
`org.wildfly.swarm.topology.openshift.runtime.NamespaceService`
contains a simple algorithm to select which namespace to target
when reading the topology. This checks the `KUBERNETES_NAMESPACE`
env var, then `OPENSHIFT_BUILD_NAMESPACE` and then possibly
the list of all projects iff it contains a single entry.

However, the `KUBERNETES_NAMESPACE` env var isn't a feature
of Kubernetes or OpenShift. It only gets added to the pod template
by the Fabric8 Maven plugin, using the Kubernetes Downward API.
If the deployment method used doesn't involve Fabric8 Maven plugin,
this env var will be missing. Then, the `OPENSHIFT_BUILD_NAMESPACE`
env var contains the name of the namespace _where the image was
built_, which doesn't have to be the name of the namespace in which
the pod _is currently running_ (though it's probably quite common).

It seems reading `/var/run/secrets/kubernetes.io/serviceaccount/namespace`
is the best option, see also
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod

Modifications
-------------
Changed the `NamespaceService` to first try reading
`/var/run/secrets/kubernetes.io/serviceaccount/namespace`.
If it fails, continue with the original algorithm.

Result
------
If the pod is running in a different namespace than the image
was built in, and Fabric8 Maven plugin wasn't involved, the namespace
is still selected correctly.

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
You tested this works with a booster or the like?

**Comment by Ladicek** [comment]
No booster uses topology-openshift. I didn't test with our topology-openshift test (which is currently failing because of this issue), because that expects a Swarm release available in some Maven repo, but I tested manually.

**Comment by kenfinnigan** [comment]
Should this check happen before KUBERNETES_NAMESPACE or just before OPENSHIFT_BUILD ?

**Comment by Ladicek** [comment]
Definitely before `OPENSHIFT_BUILD_NAMESPACE`. We can check `KUBERNETES_NAMESPACE` before or after, I don't mind.

**Comment by kenfinnigan** [comment]
Can we switch to do `KUBERNETES_NAMESPACE` first?

**Comment by Ladicek** [comment]
Done.

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
