### PR TITLE
EclipseLink as JPA provider

### PR DESCRIPTION
**Pull request by slobodanl**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

---
## Motivation

Module enables declarative configuration of EclipseLink as JPA provider.
## Modifications

New module definition with appropriate configuration assets added
## Result

Eclipselink can be enabled as JPA provider within persistance.xml
## Examples

I'll create another pull request for wildfly-swarm-examples project that utilize this module.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Ok to test

**Comment by gastaldi** [comment]
No JIRA for this PR? I guess we were supposed to merge once all the checklist items were ok?

**Comment by bobmcwhirter** [comment]
No idea why my mail comments are posting as from CI now.

**Comment by slobodanl** [comment]
I just want to get your feedback for one possible issue that i see with the
module implementation, currently the module does not have direct dependancy
to eclipselink impl and from my perspecitive feels not selfcontained. Why i
skiped at first place was just the fact to provide more freedom for child
project to decide upon version that they would use. Then i figure out that
module resource filtering is done by that point. Long story short, is it ok
to relate the module with direct dependancy to eclipselink and create
another PR?

**Pull request merged**
