### PR TITLE
THORN-1564 - Enable java.util.Properties for configurations

### PR DESCRIPTION
**Pull request by michbeck100**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

This PR enables Fractions to use `java.util.Properties` as configuration properties. This was explicitly blacklisted [here](https://github.com/thorntail/thorntail/blob/79b59c0cf3729fcd33bf1beefb9e1c931a216602/core/container/src/main/java/org/wildfly/swarm/container/runtime/ConfigurableManager.java#L70) before. But most of the code was there already. 
Also the support for `java.util.Map` and `java.util.List` seems to be complete, but stays blacklisted.

### CODE REVIEW

**Review by kenfinnigan — DISMISSED** [review]
Looks ok to me. Any comments @bobmcwhirter?

**Comment by michbeck100** [comment]
There seems to be general problem with the semaphore builds. It fails at `mvn clean`.

**Comment by michbeck100** [comment]
Had to add the snapshot repository for thorntail-maven-plugin to fix the semaphore build (674af97).

**Comment by kenfinnigan** [comment]
Semaphore build only works with 4.x, so adding the snapshot repository isn't needed

**Comment by michbeck100** [comment]
Reverted with 071a6e6

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
