### PR TITLE
SWARM-1635: Added FT detector

### PR DESCRIPTION
**Pull request by heiko-braun**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by heiko-braun** [comment]
retest this please

**Review by kenfinnigan — APPROVED** [review]

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
test this please

**Comment by heiko-braun** [comment]
Given that the main tests pass (https://ci.wildfly-swarm.io/job/pr-linux-2/2/) I am going to merge this.

**Pull request merged**
