### PR TITLE
[ENTSWM-738] in product docs, link to community variant of SwarmProperties class

### PR DESCRIPTION
**Pull request by Ladicek**
- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
@tradej This is to make sure product docs link to a correct version of the `SwarmProperties` class. Product tags don't exist in this repo, but linking to the corresponding community tag should be fine. WDYT?

**Comment by sangeetaraghu** [comment]
@tradej Will we have to update the community version in the split Runtimes repos?

**Comment by tradej** [comment]
@Ladicek I get the need for the change, but why are we not setting `<communityVersion>${version}</communityVersion>` in the POM? If there's a reason, I'd only conditionalise the link and not the text of the note, but otherwise LGTM.

**Comment by tradej** [comment]
@sangeetaraghu We will pull this change once it's merged and in the prod repository. We will use the `sync-thorntail` script. We may or may not have to do some further adjustments in our repos, but we will not be _duplicating_ the changes as such.

**Comment by Ladicek** [comment]
> why are we not setting `<communityVersion>${version}</communityVersion>` in the POM?

Weeeeellllll... that's a good point. There's no reason why we couldn't do that in community. We fix it in product anyway.

EDIT: actually, no. We could set `<version.certified-community>${project.version}</version.certified-community>`, as _that_ is the one we fix in product. But that would have the same meaning.

EDIT2: actually even better, we already have a property that is set to `${project.version}` in community and to `${version.certified-community}` in product -- it's `version.wildfly.swarm`. Using that would be best. Thanks for poking into it :-)

**Comment by tradej** [comment]
@Ladicek The current version looks good IMO. @inoxx03, can you please verify that?

**Comment by sangeetaraghu** [comment]
@Ladicek There is one more occurrence of Javadocs in the guide. Can you please make the same change here too?

**See the org.wildfly.swarm.config.logging.Level class for the list of available levels.** 
--- where the link is:
https://thorntail.github.io/javadocs/2.5.0.Final-redhat-00016/apidocs/org/wildfly/swarm/config/logging/Level.html

**Comment by Ladicek** [comment]
I'll check, should be easy.

**Comment by Ladicek** [comment]
Fixed. I also verified locally that it works both in community and product build.

**Comment by inoxx03** [comment]
@Ladicek @tradej @sangeetaraghu The changes look good to me. Once this PR is merged, we will pull the changes into the Thorntail Product docs repo using our content sync script. We will have to rename the `version` attribute that we override [in the `master.adoc` file](https://gitlab.cee.redhat.com/red-hat-openshift-application-runtimes-documentation/thorntail/blob/master/docs/runtime-guide/master.adoc#L92) of the Thorntail Product runtime guide. Once we do that, the version in the URL will resolve properly.

EDIT: in addition to renaming the attribute in the `master.adoc` file we will need to set it to point to the community release version of Thorntail. Either way, this is a rather small and uncomplicated change and we can make it anytime.

**Comment by Ladicek** [comment]
@inoxx03 I'm not sure why you'd have to rename the `version` attribute, as this is rendered as part of Thorntail build, but I trust you know what you're doing :-)

**Comment by Ladicek** [comment]
Also, there's been no objection, so I'm gonna merge this (and also submit a PR to the product repo).

**Comment by inoxx03** [comment]
@Ladicek Good point. maybe I can avoid renaming the attribute and just change the referenced attribute name to match the one that contains the community release version string. At any rate, I have no objections, please go ahead and merge this PR and file one for the changes on the TT product repo. Once you merge that I will take it form there and sync the changes to the TT product docs repo:) thank you:)

**Pull request merged**
