### PR TITLE
Utilize the SmallRye OpenAPI library (smallrye-open-api 1.0.0) [for Thorntail 4.x]

### PR DESCRIPTION
**Pull request by EricWittmann**
This fixes issue #972 for v4 of Thorntail.

- [*] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [*] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [*] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by EricWittmann** [comment]
Whoops - didn't realize how the checkboxes worked.  Sorry about that screwup. :(

**Comment by sberyozkin** [comment]
Hi Eric, can you please resolve the bom/pom.xml conflict ?

**Comment by EricWittmann** [comment]
OK should be resolved.

**Comment by sberyozkin** [comment]
Thanks

**Review by sberyozkin — APPROVED** [review]
LGTM, Ken, Bob, I'll merge tomorrow morning if you'll have no objections before that, thanks

**Pull request merged**
