### PR TITLE
SWARM-1404: Added Servlet integration to OpenTracing fraction

### PR DESCRIPTION
**Pull request by jpkrohling**
Motivation
----------
The OpenTracing fraction provides only access to the OpenTracing
libraries, without any "out of the box" added value, other than
a ready-to-use OpenTracing integration.

As we can always assume that there will be a servlet engine working
for any Swarm application, we can expand the added value to include
automatic span reporting via the Servlet framework integration from
the OpenTracing contrib repository.

Modifications
-------------
* Added the Servlet framework integration to the OpenTracing fraction
* Improved the OpenTracing test to also test this integration

Result
------
Applications using the OpenTracing fraction now get out-of-the-box
span reports, one span per request. Business spans can be created
as a child of the request span (see test), or as independent spans.

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
add to whitelist

**Comment by jpkrohling** [comment]
Once this is merged, I'll publish an example using this. Should the example be part of Swarm examples ( https://github.com/wildfly-swarm/wildfly-swarm-examples ) , or located at one of our repositories?

**Comment by kenfinnigan** [comment]
In our examples repo is good

**Comment by jpkrohling** [comment]
Example: https://github.com/wildfly-swarm/wildfly-swarm-examples/pull/149

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
