### PR TITLE
THORN-2466: Demonstrate unused ObjectMapper

### PR DESCRIPTION
**Pull request by samolsen**
Motivation
----------
Add unit tests demonstrating a customized
Jackson ObjectMapper is not used by JAX-RS

Modifications
-------------
Added unit tests demonstrating this bug

Result
------
Causes build to fail due to incorrect behavior

- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
ok to test

**Comment by Ladicek** [comment]
I just pushed 2 commits to your branch, the 1st makes tests in this module considerably simpler, and the 2nd fixes your problem. Its commit message includes details. WDYT?

**Comment by samolsen** [comment]
That looks great to me, and the commit explanation really clarifies how the framework behaves. Thank you!

**Comment by Ladicek** [comment]
Great, thanks! I'll let Jenkins finish the tests and, assuming they pass, merge this PR.

**Comment by roguexz** [comment]
Thank you for the clarification @Ladicek. I was running in to this issue a couple of days ago and was wondering why my tests were failing (when I distinctly remember) them passing earlier :)

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Thanks!

**Comment by roguexz** [comment]
Also a small observation. It is better to instantiate the ObjectMapper once and then use that instance, instead of creating it every time the provider is instantiated.

I ran into a peculiar big where I was trying to make multiple REST calls using ForkJoin and I would see random failures around de-serialization. I had custom Jackson extensions and modules, which wouldn't load due to some race condition. So I moved the object mapper instantiation to a static block and reused that instance.

**Comment by Ladicek** [comment]
Good point!

**Pull request merged**
