### PR TITLE
THORN-2289: Update to WildFly 15

### PR DESCRIPTION
**Pull request by kenfinnigan**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------
WildFly 15 is available.

Modifications
-------------
Update WildFly versioning to 15.

Result
------
WildFly 15 is the base for Java EE fractions.

### CODE REVIEW

**Comment by sberyozkin** [comment]
Should nosql-config-api be updated as well ?

**Comment by kenfinnigan** [comment]
Forgot to ask @scottmarlow about that!

Something you can do @scottmarlow? Not likely to release until early Jan

**Comment by manovotn** [comment]
Since we are moving to wfly 15, I know @Ladicek made some workaround for https://issues.jboss.org/browse/WFLY-11373.
Namely this commit - https://github.com/thorntail/thorntail/commit/a049de34f7feb74538a04a7a010b5e967e0ab355
@kenfinnigan since the fix for it got into wfly 15, we should be able to remove changes made to `MicroProfileFaultToleranceExtension`.

**Comment by kenfinnigan** [comment]
Or leave it as I don't think that fix made it into EAP, and we would need it there anyway

**Comment by manovotn** [comment]
Oh, right, didn't think of that, sorry.

**Comment by kenfinnigan** [comment]
No problem. It was a good idea. I like removing code

**Comment by sberyozkin** [comment]
Ken, I submitted https://github.com/thorntail/nosql-config-api/pull/5, please approve/merge, and I can release tomorrow. Or you can just press a CI no-sql release button, worked for me just fine the other day

**Comment by juangon** [comment]
Retest this please

**Comment by juangon** [comment]
Retest this please

**Comment by sberyozkin** [comment]
Ken, nosql-config-api 1.6.0 should be in Central shortly

**Review by Ladicek — DISMISSED** [review]

**Comment by Ladicek** [comment]
This looks Obviously Good (TM), but will make version alignment with EAP more complex, as EAP 7.2 (looking at the latest candidate) is still technically based on WildFly 14 (even if it's closer to 15).

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I think this is technically OK. We do need the decision whether to go with it or not.

**Pull request merged**
