### PR TITLE
SWARM-1392: Create a separate bom to manage versions in user project builds

### PR DESCRIPTION
**Pull request by heiko-braun**
Simple preview to discuss further steps. Not intended to be merged yet

### CODE REVIEW

**Comment by heiko-braun** [comment]
@kenfinnigan Is this similar to what you had in mind?

**Comment by kenfinnigan** [comment]
Yes, with a couple of changes. I think `dependency-bom` is a more appropriate name.

Also, I wasn't expecting http components to be in there, I was only expecting openjdk-orb and whatever else was causing the issues before

**Comment by heiko-braun** [comment]
I think we would need all of the pending DR3 ones to managed. httpclient is one of them I used to test the setup.

**Comment by kenfinnigan** [comment]
I didn't think there was a duplicate version issue with httpclient?

**Comment by heiko-braun** [comment]
not problem with duplicates, but the version was not aligned with a prod one. see the DR3 tab in @mswiderski report

**Comment by kenfinnigan** [comment]
I have no idea which report that is, can you share a link via email?

**Comment by kenfinnigan** [comment]
Thanks for the changes.

If we can adjust name to `dependency-bom` I think we're good to merge, when it passes

**Comment by heiko-braun** [comment]
retest this please

**Pull request merged**
