### PR TITLE
SWARM-482: Management console fraction 

### PR DESCRIPTION
**Pull request by gastaldi**
It's working great now after Ken's hint of creating a separate UI module. 
Ready to be merged.

### CODE REVIEW

**Comment by gastaldi** [comment]
I guess the reason why Artifact Not Found exception is given when running from a swarmed app is because the `management-console/api/target/classes/META-INF/wildfly-swarm-classpath.conf` file is generated with the following content: 

```
maven(org.jboss.as:jboss-as-console) remove
maven(org.jboss.as:jboss-as-console-resources) remove
```

How do I prevent them to be removed?

**Comment by kenfinnigan** [comment]
The way swagger does it is to create a swagger-ui maven module that performs the extraction from the war into our war, and then that module is included in swagger-api

**Comment by bobmcwhirter** [comment]
You can provide that file to prevent generation. Or something Ken can
suggest.

## 

Sent from my iPhone

On Jun 3, 2016, at 7:50 PM, George Gastaldi notifications@github.com
wrote:

I guess the reason why Artifact Not Found exception is given when running
from a swarmed app is because the
management-console/api/target/classes/META-INF/wildfly-swarm-classpath.conf
file is generated with the following content:

maven(org.jboss.as:jboss-as-console) remove
maven(org.jboss.as:jboss-as-console-resources) remove

How do I prevent them to be removed?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/wildfly-swarm/wildfly-swarm-core/pull/41#issuecomment-223662348,
or mute the thread
https://github.com/notifications/unsubscribe/AAA-T3gbSir3c1mowd4AeNp9zZfDTbdqks5qIHeDgaJpZM4ItCZQ
.

**Comment by kenfinnigan** [comment]
Don't know if providing it would work, as it's no longer an either or.

It now adds more to that file if it exists, as opposed to not doing anything

**Comment by gastaldi** [comment]
This is the JAR that is excluded: http://central.maven.org/maven2/org/jboss/as/jboss-as-console/2.8.25.Final/jboss-as-console-2.8.25.Final-resources.jar

**Comment by gastaldi** [comment]
Works great now, created an UI module just as it was done in the Swagger fraction

**Pull request merged**
