### PR TITLE
THORN-2185: Change config keys to 'thorntail.'

### PR DESCRIPTION
**Pull request by kenfinnigan**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------
It's confusing to have a root config key of 'swarm' when the project is named Thorntail.

Modifications
-------------
Modified config handling to convert 'swarm' to 'thorntail', for backwards compatibility, and updated all config keys to start with 'thorntail'.

Result
------
Config keys now start with 'thorntail', but 'swarm' still works as well.

### CODE REVIEW

**Comment by Ladicek** [comment]
I've noticed that a top-level `swarm` key in YAML is automatically transformed to `thorntail`. Are we doing the same for system properties? I.e., will `swarm.*` system properties still work?

(One option how to achieve that is to scan all system properties and clone all that begin with `swarm.*` to a `thorntail.*` equivalent, somewhere soon enough in the boot process. But I guess there are other options, too.)

**Comment by kenfinnigan** [comment]
Pretty sure env vars are already mapped, as they're sucked into ConfigKeys which does the rename from `swarm` to `thorntail`

**Comment by Ladicek** [comment]
I totally forgot to say that I consider this pretty risky. For the system properties, we also access a lot of them through other means than the config system, often simply by `System.getProperty`.

**Comment by kenfinnigan** [comment]
All those usages should also have been adjusted to use "thorntail"

**Comment by Ladicek** [comment]
Yea, and if my understanding is correct, those places will no longer accept the `swarm.*` variant. As in, we won't provide compatibility. That's my concern.

**Pull request merged**
