### PR TITLE
Bump tck to 1.0.1 and fix the one failing test.

### PR DESCRIPTION
**Pull request by pilhuhn**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----
This is SWARM-1718 -- forgot to add it to the description earlier as my branch was already named after it :)

### CODE REVIEW

**Comment by kenfinnigan** [comment]
add to whitelist

**Comment by kenfinnigan** [comment]
@pilhuhn can this be merged and considered to be passing MP 1.2 TCK, or do we need to wait to merge until after we've released?

**Comment by pilhuhn** [comment]
@kenfinnigan It is a superset of the MP-Metrics 1.0 TCK, that includes the tests from MP-Metrics 1.0 and some fixes and some additional ones where the spec has a requirement, but the 1.0 TCK did not test it.
MP-Metrics 1.0 is included in MP-1.2

**Comment by kenfinnigan** [comment]
So updating MP Metrics to 1.0.1 won't stop us passing the 1.0.0 TCK for it?

If I'm understanding correctly

**Comment by pilhuhn** [comment]
This is how I understand it as well.
There are no tests in the Metrics 1.0 tck that check that an implementation only has 1.0 implementation (in fact the impl stayed the same between 1.0 and 1.0.1 and only 1.0.1 adds more tests)

**Comment by kenfinnigan** [comment]
Interestingly testsuite-microprofile-metrics failed but not TCK.

Would that be expected? I know we're looking to remove that testsuite, so not sure how critical it failing is?

**Comment by kenfinnigan** [comment]
retest this please

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
