### PR TITLE
[SWARM-1075] Deprecate camel-other in favour of specific fractions

### PR DESCRIPTION
**Pull request by tdiesler**
- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
As I mentioned the other day, we don't want to have hundreds of fractions for every single Camel component.

I'd prefer to come up with a solution whereby purely module.xml fractions can be utilized on the fly without needing an entire fraction module at build time

**Comment by tdiesler** [comment]
This PR adds fractions for activemq, ognl, and swagger. When this other solution exists, we can of course revisit the set of twelve camel fractions that currently exist. camel-other nevertheless needs to be deprecated and references to it need to be replaced.

**Comment by kenfinnigan** [comment]
Right, but these fractions are purely module.xml files right?

As I said I want a solution to purely module.xml fractions instead of adding more and more fractions

**Comment by tdiesler** [comment]
No problem, I can wait for this "other solution" to show up.

In the meantime, these references to camel-other should still be removed so they don't make it into the next swarm release.

```
[tdiesler@macbook wildfly-swarm]$ git grep camel-other
fractions/camel/components/other/pom.xml:  <artifactId>camel-other</artifactId>
pom.xml:        <artifactId>camel-other</artifactId>
pom.xml:        <module>testsuite/testsuite-camel-other</module>
testsuite/testsuite-camel-other/pom.xml:  <artifactId>testsuite-camel-other</artifactId>
testsuite/testsuite-camel-other/pom.xml:      <artifactId>camel-other</artifactId>

[tdiesler@macbook wildfly-swarm-examples]$ git grep camel-other
camel/camel-swagger/pom.xml:      <artifactId>camel-other</artifactId>
```

**Pull request closed without merging**
