### PR TITLE
THORN-2411: implement MicroProfile RestClient 1.3

### PR DESCRIPTION
**Pull request by Ladicek**
Motivation
----------
MP RestClient 1.3 is part of MP 3.0.

Modifications
-------------
SmallRye RestClient was moved to RESTEasy. So this commit
removes all dependencies on SmallRye RestClient and instead
updates RESTEasy to version 3.8.0 which implements
MP RestClient 1.3. This RESTEasy version is newer than
what WildFly 15.0.1 has, so we need to override some
module definitions.

Result
------
RESTEasy 3.8.0 is used and MP RestClient 1.3 is supported.

- [x] Have you followed the guidelines in our [Contributing](https://thorntail.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by sberyozkin** [comment]
@Ladicek I think it looks very precise. But what happens if someone has a `jaxrs` fraction and `microprofile-rest-client` ones, would there be a risk of different RestEasy version clashing ?

**Comment by Ladicek** [comment]
So that's exactly why the `module-rewrite.conf` replaces a version string of all RESTEasy artifacts in all (`ALL:ALL`) `module.xml` files with 3.8.0.Final. Unless I missed some artifact, there should be no way how multiple RESTEasy versions could come in.

**Comment by sberyozkin** [comment]
OK, so via this mechanism we move to 3.8.0.Final across the board and it would be dropped once we move to WF 17...

**Comment by Ladicek** [comment]
Yes, exactly.

**Review by sberyozkin — DISMISSED** [review]

**Comment by Ladicek** [comment]
> Unless I missed some artifact

I actually found one :-), fixed now.

**Comment by Ladicek** [comment]
I'll investigate the failures, they are all in `testsuite-microprofile-restclient`.

**Comment by Ladicek** [comment]
Test failures have been caused by MP RestClient 1.3 prescribing a default value of the `Accept` header to be `application/json` unless the client interface specifies otherwise. Which is clearly a breaking change.

**Comment by sberyozkin** [comment]
Yes, Produces fixes it. (Might be interesting to check if ClientHeaderParam works instead when no Produces available but it is definitely not related to this upgrade :-) )

**Review by sberyozkin — APPROVED** [review]

**Pull request merged**
