### PR TITLE
Re-enable the microprofile fractions

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
@heiko-braun I'd already started working on this Thursday.

It's not as simple as reverting the commits as there are tests that were deactivated in MP 1.2 PR that are now failing with it present.

**Comment by heiko-braun** [comment]
@kenfinnigan Do you want me to continue with this? I can look at the tests, as they probably relate to areas that I contributed/changed anyway.

**Comment by kenfinnigan** [comment]
Have a build running now that I think fixes it, will now soon

**Comment by heiko-braun** [comment]
great thanks. closing this.

**Pull request closed without merging**
