### PR TITLE
SWARM-2021: Dependencies from a Dependency Tree are not in the classpath

### PR DESCRIPTION
**Pull request by pieralexandre**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
ok to test

**Comment by pieralexandre** [comment]
@kenfinnigan you can test the fix with the simple maven project in SWARM-2021 that will throw a ClassNotFoundException. To test the fix, you can start the project with the VM argument -Dswarm.cp.info with the yaml file provided in dependenciez.zip file.
[dependencies.zip](https://github.com/wildfly-swarm/wildfly-swarm/files/1974543/dependencies.zip)
[SWARM-2021.zip](https://github.com/wildfly-swarm/wildfly-swarm/files/1974540/SWARM-2021.zip)

**Comment by pieralexandre** [comment]
@kenfinnigan Jenkins fails because "java.nio.file.FileSystemException: C:\opt\jenkins\workspace\wildfly-swarm-pull-request-windows\boms\bom-stable\target\m2repo\org\apache\lucene\lucene-highlighter: There is not enough space on the disk."

**Comment by mkouba** [comment]
The windows build failure is a known MP FT TCK issue.

**Review by mkouba — APPROVED** [review]
Looks good.

**Pull request merged**
