### PR TITLE
SWARM-1052: Wrong path is resolved in the HealthAnnotationProcessor.p…

### PR DESCRIPTION
**Pull request by hei1233212000**
…rocessArchive()

Motivation
----------
fix the wrong path resolved in the HealthAnnotationProcessor.processArchive()

Modifications
-------------
changed to use the safeAppend() for resolving the path declared on method level

Result
------
Now the path of Health endpoint could be resolved correctly(aligned with JAX-RS)

- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
ok to test

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Comment by hei1233212000** [comment]
Hi Ken, are you asking me to retest it?
I tested with the test case in [SWARM-1052](https://issues.jboss.org/browse/SWARM-1052) and there is NO problem.

**Comment by bobmcwhirter** [comment]
No that's a signal for our CI to run the tests again.

**Comment by kenfinnigan** [comment]
Sorry @hei1233212000, we had an issue with our CI server yesterday that meant by attempt yesterday to retest failed, so I did it again today

**Comment by hei1233212000** [comment]
got it, I do not know that lol
Thanks :)

**Review by heiko-braun — APPROVED** [review]

**Pull request merged**
