### PR TITLE
THORN-2089 upgrade wildfly-nosql to 1.0.0.Beta1 and nosql-config-api to 1.3.1

### PR DESCRIPTION
**Pull request by scottmarlow**

### CODE REVIEW

**Comment by mkouba** [comment]
Hey @scottmarlow, what's the difference between 1.3.0 and 1.3.1? I cannot see anything.

**Comment by scottmarlow** [comment]
@mkouba the only change is that I updated wildfly-nosql from alpha to beta, getting ready for first 1.0 final.  From a project coordination correctness point of view, I thought we should regenerate the config, but yes, no change needed.  Should we stich with 1.3.0 of nosql config?

**Comment by mkouba** [comment]
I'm not sure. @kenfinnigan what's your opinion?

**Comment by kenfinnigan** [comment]
I don't have a preference

**Comment by scottmarlow** [comment]
I'll sync with master, to address being out of date.  

With regard to the other underlying question, of whether we should bump a minor release of nosql-config-api, when releasing a wildfly-nosql update.  I don't plan any actual api changes, in the wildfly-nosql subsystems until the next wildfly-nosql version, of which I would like to start on.  

So, I think the take away for me, is that I won't release another new nosql-config-api until wildfly-nosql 1.1/2.0 release.

**Comment by scottmarlow** [comment]
@mkouba I reverted back to use 1.3.0 for nosql config.

**Review by mkouba — APPROVED** [review]

**Comment by mkouba** [comment]
The windows build failed with usual MP FT TCK failure (BulkheadAsynchRetryTest).

**Comment by scottmarlow** [comment]
@mkouba do people merge their own PRs for simple changes like this or is it best to always have someone else merge?  

Second question, do you all want me to approve/merge changes like this pr if they come from someone else?  I seem to have commit rights now, thanks, but wanted to make sure that was intentional before using them.

**Comment by mkouba** [comment]
> @mkouba do people merge their own PRs for simple changes like this or is it best to always have someone else merge?

Sometimes yes, esp. when someone else approved the PR. But I think it's usually better when someone else merge... I can merge this one.

> Second question, do you all want me to approve/merge changes like this pr if they come from someone else? I seem to have commit rights now, thanks, but wanted to make sure that was intentional before using them

I'd say we would be happy if you review/approve PRs where someone requested you to do so (in a comment or github reviewers).

**Pull request merged**
