### PR TITLE
Using Object::notNull in lambda expressions

### PR DESCRIPTION
**Pull request by gastaldi**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by kenfinnigan** [comment]
why no JIRA?

**Comment by gastaldi** [comment]
Because it is too trivial. It was part of my investigation on https://issues.jboss.org/browse/SWARM-847 but does not fix it.

**Comment by kenfinnigan** [comment]
Why is it too trivial?

There's clearly a problem with nulls being passed

**Comment by gastaldi** [comment]
Nulls are already handled in the original code. This is just to use Objects::nonNull instead of e->e!=null

**Comment by kenfinnigan** [comment]
Then why make the change?

To me this is refactoring for no real purpose.

If we want to go through the entire code based to do this kind of refactoring then its something we should discuss. I'd prefer we don't do it piecemeal

**Comment by kenfinnigan** [comment]
Closing this as it's not related to a fix, or JIRA, and if we're going to look at "cleaning up" the code base we should do it on a larger scale than just a single class

**Pull request closed without merging**
