### PR TITLE
SWARM-1892: Add a testsuite for the MVC fraction

### PR DESCRIPTION
**Pull request by gtudan**
Motivation
----------
We want a testsuite that checks the basic functions of the MVC fraction

Modifications
-------------
* A test was added that installs the fraction and tests that ozark is
activated and views can be rendered.
* The MVC-fraction now uses a deployment module to activate ozark

Result
------
The MVC fraction is covered by automatic tests

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by Ladicek** [comment]
I can't comment on the changes in the fraction itself, but the test looks exactly like I'd expect it to!

**Comment by gtudan** [comment]
Sorry about those changes on the fraction itself. The tests revealed that I got some aspects of authoring a fraction wrong and these needed to be fixed in order to get the tests running. Should I put those in a sepperate PR?

**Comment by Ladicek** [comment]
No no no, changing the fraction is absolutely fine, I'm just saying I don't feel qualified to review them :-)

**Review by sberyozkin — COMMENTED** [review]
Hi. sorry for a delay, my knowledge of the modules mechanism is very limited at the moment but it looks like exactly what other fractions do and what I tried in my own fraction work, it looks good. Hope Ken will approve when he gets back :-). Thanks for getting this MVC test PR done

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Review by kenfinnigan — APPROVED** [review]

**Comment by gtudan** [comment]
Thank you Ken!

**Pull request merged**
