### PR TITLE
SWARM-1043: Show the logs of Configurable values defined in ArchivePreparer

### PR DESCRIPTION
**Pull request by emag**
- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
 - https://issues.jboss.org/browse/SWARM-1043
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

Motivation
----------
It'd be good if showing the following Configuralble values defined in some ArchivePreparers.

* swarm.context.path
* swarm.keycloak.json.path
* swarm.keycloak.security.constraints

Modifications
-------------
Move these fields to each fraction(Undertow/Keycloak Fraction).

Result
------
You can see these values in the boot log.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Can you comment @bobmcwhirter on whether @AttributeDocumentation is only picked up from a *Fraction class?

**Comment by bobmcwhirter** [comment]
Should be picked up anywhere a Configurable would be but I'd need to
verify.

Bob

**Comment by kenfinnigan** [comment]
retest this please

**Comment by bobmcwhirter** [comment]
Looking at the commit, it seems to be adding configurables for a few things (keycloak.json.path) along with documentation?

The $subject made me initially think it was changing how we scrub around for configurables in ArchivePreparers generically speaking.

**Comment by kenfinnigan** [comment]
It does also move from @Configurable usage from ArchivePreparer into *Fraction and then inject *Fraction into ArchivePreparer

**Comment by emag** [comment]
@bobmcwhirter sorry for confusing. This commit aims at showing some Configurables in boot-logs but mixed adding @ AttributeDocumentation to them, 2 tasks in 1 commit...

In the first place should the Configurables in ArchivePreparer be picked by ConfigurableManager or something as you said?

**Comment by bobmcwhirter** [comment]
Yah, the they should be picked up in ArchivePreparer, or wherever @Configurables are allowed.  If they aren't, that'd be a bug, for certain.

**Comment by emag** [comment]
OK, I see. my approach is wrong apparently. I'm closing this P-R.

**Pull request closed without merging**
